// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: depthCams.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_depthCams_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_depthCams_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_depthCams_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_depthCams_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_depthCams_2eproto;
namespace DepthCameras {
class Acknowledge;
struct AcknowledgeDefaultTypeInternal;
extern AcknowledgeDefaultTypeInternal _Acknowledge_default_instance_;
class CameraStatusUpdate;
struct CameraStatusUpdateDefaultTypeInternal;
extern CameraStatusUpdateDefaultTypeInternal _CameraStatusUpdate_default_instance_;
class CommandStatusUpdate;
struct CommandStatusUpdateDefaultTypeInternal;
extern CommandStatusUpdateDefaultTypeInternal _CommandStatusUpdate_default_instance_;
class DcRequest;
struct DcRequestDefaultTypeInternal;
extern DcRequestDefaultTypeInternal _DcRequest_default_instance_;
class DcResponse;
struct DcResponseDefaultTypeInternal;
extern DcResponseDefaultTypeInternal _DcResponse_default_instance_;
}  // namespace DepthCameras
PROTOBUF_NAMESPACE_OPEN
template<> ::DepthCameras::Acknowledge* Arena::CreateMaybeMessage<::DepthCameras::Acknowledge>(Arena*);
template<> ::DepthCameras::CameraStatusUpdate* Arena::CreateMaybeMessage<::DepthCameras::CameraStatusUpdate>(Arena*);
template<> ::DepthCameras::CommandStatusUpdate* Arena::CreateMaybeMessage<::DepthCameras::CommandStatusUpdate>(Arena*);
template<> ::DepthCameras::DcRequest* Arena::CreateMaybeMessage<::DepthCameras::DcRequest>(Arena*);
template<> ::DepthCameras::DcResponse* Arena::CreateMaybeMessage<::DepthCameras::DcResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace DepthCameras {

enum MessageType : int {
  MESSAGE_TYPE_UNSPECIFIED = 0,
  MESSAGE_TYPE_ACK_REPLY = 1,
  MESSAGE_TYPE_COMMAND_STATUS = 2,
  MESSAGE_TYPE_GENERIC_QUERY = 3,
  MESSAGE_TYPE_HEARTBEAT = 4,
  MESSAGE_TYPE_BAG_STATE_REQUEST = 5,
  MESSAGE_TYPE_BAG_STATE = 6,
  MESSAGE_TYPE_CAMERA_STATUS = 7,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = MESSAGE_TYPE_UNSPECIFIED;
constexpr MessageType MessageType_MAX = MESSAGE_TYPE_CAMERA_STATUS;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
enum DcCommandType : int {
  DC_COMMAND_UNSPECIFIED = 0,
  DC_COMMAND_NOP = 1,
  DC_COMMAND_GENERIC_QUERY = 2,
  DcCommandType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DcCommandType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DcCommandType_IsValid(int value);
constexpr DcCommandType DcCommandType_MIN = DC_COMMAND_UNSPECIFIED;
constexpr DcCommandType DcCommandType_MAX = DC_COMMAND_GENERIC_QUERY;
constexpr int DcCommandType_ARRAYSIZE = DcCommandType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DcCommandType_descriptor();
template<typename T>
inline const std::string& DcCommandType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DcCommandType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DcCommandType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DcCommandType_descriptor(), enum_t_value);
}
inline bool DcCommandType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DcCommandType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DcCommandType>(
    DcCommandType_descriptor(), name, value);
}
enum DcCameraStatusCodes : int {
  CAMERA_STATUS_CONNECTED = 0,
  CAMERA_STATUS_NO_FRAME = -1,
  CAMERA_STATUS_STD_EXCEPTION = -2,
  CAMERA_STATUS_RECOVERABLE_EXCEPTION = -3,
  CAMERA_STATUS_NOT_RECOVERABLE_EXCEPTION = -4,
  DcCameraStatusCodes_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DcCameraStatusCodes_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DcCameraStatusCodes_IsValid(int value);
constexpr DcCameraStatusCodes DcCameraStatusCodes_MIN = CAMERA_STATUS_NOT_RECOVERABLE_EXCEPTION;
constexpr DcCameraStatusCodes DcCameraStatusCodes_MAX = CAMERA_STATUS_CONNECTED;
constexpr int DcCameraStatusCodes_ARRAYSIZE = DcCameraStatusCodes_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DcCameraStatusCodes_descriptor();
template<typename T>
inline const std::string& DcCameraStatusCodes_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DcCameraStatusCodes>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DcCameraStatusCodes_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DcCameraStatusCodes_descriptor(), enum_t_value);
}
inline bool DcCameraStatusCodes_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DcCameraStatusCodes* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DcCameraStatusCodes>(
    DcCameraStatusCodes_descriptor(), name, value);
}
enum DcStatusCodes : int {
  STATUS_CODE_SUCCESS = 0,
  STATUS_CODE_FAILED = -1,
  DcStatusCodes_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DcStatusCodes_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DcStatusCodes_IsValid(int value);
constexpr DcStatusCodes DcStatusCodes_MIN = STATUS_CODE_FAILED;
constexpr DcStatusCodes DcStatusCodes_MAX = STATUS_CODE_SUCCESS;
constexpr int DcStatusCodes_ARRAYSIZE = DcStatusCodes_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DcStatusCodes_descriptor();
template<typename T>
inline const std::string& DcStatusCodes_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DcStatusCodes>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DcStatusCodes_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DcStatusCodes_descriptor(), enum_t_value);
}
inline bool DcStatusCodes_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DcStatusCodes* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DcStatusCodes>(
    DcStatusCodes_descriptor(), name, value);
}
// ===================================================================

class Acknowledge final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DepthCameras.Acknowledge) */ {
 public:
  inline Acknowledge() : Acknowledge(nullptr) {}
  ~Acknowledge() override;
  explicit PROTOBUF_CONSTEXPR Acknowledge(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Acknowledge(const Acknowledge& from);
  Acknowledge(Acknowledge&& from) noexcept
    : Acknowledge() {
    *this = ::std::move(from);
  }

  inline Acknowledge& operator=(const Acknowledge& from) {
    CopyFrom(from);
    return *this;
  }
  inline Acknowledge& operator=(Acknowledge&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Acknowledge& default_instance() {
    return *internal_default_instance();
  }
  static inline const Acknowledge* internal_default_instance() {
    return reinterpret_cast<const Acknowledge*>(
               &_Acknowledge_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Acknowledge& a, Acknowledge& b) {
    a.Swap(&b);
  }
  inline void Swap(Acknowledge* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Acknowledge* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Acknowledge* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Acknowledge>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Acknowledge& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Acknowledge& from) {
    Acknowledge::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Acknowledge* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DepthCameras.Acknowledge";
  }
  protected:
  explicit Acknowledge(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandIdFieldNumber = 2,
    kTypeFieldNumber = 1,
    kAcknowledgedTypeFieldNumber = 3,
  };
  // string command_id = 2;
  void clear_command_id();
  const std::string& command_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command_id();
  PROTOBUF_NODISCARD std::string* release_command_id();
  void set_allocated_command_id(std::string* command_id);
  private:
  const std::string& _internal_command_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command_id(const std::string& value);
  std::string* _internal_mutable_command_id();
  public:

  // .DepthCameras.MessageType type = 1;
  void clear_type();
  ::DepthCameras::MessageType type() const;
  void set_type(::DepthCameras::MessageType value);
  private:
  ::DepthCameras::MessageType _internal_type() const;
  void _internal_set_type(::DepthCameras::MessageType value);
  public:

  // .DepthCameras.MessageType acknowledged_type = 3;
  void clear_acknowledged_type();
  ::DepthCameras::MessageType acknowledged_type() const;
  void set_acknowledged_type(::DepthCameras::MessageType value);
  private:
  ::DepthCameras::MessageType _internal_acknowledged_type() const;
  void _internal_set_acknowledged_type(::DepthCameras::MessageType value);
  public:

  // @@protoc_insertion_point(class_scope:DepthCameras.Acknowledge)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_id_;
    int type_;
    int acknowledged_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_depthCams_2eproto;
};
// -------------------------------------------------------------------

class CommandStatusUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DepthCameras.CommandStatusUpdate) */ {
 public:
  inline CommandStatusUpdate() : CommandStatusUpdate(nullptr) {}
  ~CommandStatusUpdate() override;
  explicit PROTOBUF_CONSTEXPR CommandStatusUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CommandStatusUpdate(const CommandStatusUpdate& from);
  CommandStatusUpdate(CommandStatusUpdate&& from) noexcept
    : CommandStatusUpdate() {
    *this = ::std::move(from);
  }

  inline CommandStatusUpdate& operator=(const CommandStatusUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline CommandStatusUpdate& operator=(CommandStatusUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CommandStatusUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const CommandStatusUpdate* internal_default_instance() {
    return reinterpret_cast<const CommandStatusUpdate*>(
               &_CommandStatusUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CommandStatusUpdate& a, CommandStatusUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(CommandStatusUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CommandStatusUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CommandStatusUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CommandStatusUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CommandStatusUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CommandStatusUpdate& from) {
    CommandStatusUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CommandStatusUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DepthCameras.CommandStatusUpdate";
  }
  protected:
  explicit CommandStatusUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandIdFieldNumber = 2,
    kMsgTypeFieldNumber = 1,
    kStatusCodeFieldNumber = 3,
  };
  // string command_id = 2;
  void clear_command_id();
  const std::string& command_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command_id();
  PROTOBUF_NODISCARD std::string* release_command_id();
  void set_allocated_command_id(std::string* command_id);
  private:
  const std::string& _internal_command_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command_id(const std::string& value);
  std::string* _internal_mutable_command_id();
  public:

  // .DepthCameras.MessageType msg_type = 1;
  void clear_msg_type();
  ::DepthCameras::MessageType msg_type() const;
  void set_msg_type(::DepthCameras::MessageType value);
  private:
  ::DepthCameras::MessageType _internal_msg_type() const;
  void _internal_set_msg_type(::DepthCameras::MessageType value);
  public:

  // int32 status_code = 3;
  void clear_status_code();
  int32_t status_code() const;
  void set_status_code(int32_t value);
  private:
  int32_t _internal_status_code() const;
  void _internal_set_status_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:DepthCameras.CommandStatusUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_id_;
    int msg_type_;
    int32_t status_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_depthCams_2eproto;
};
// -------------------------------------------------------------------

class CameraStatusUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DepthCameras.CameraStatusUpdate) */ {
 public:
  inline CameraStatusUpdate() : CameraStatusUpdate(nullptr) {}
  ~CameraStatusUpdate() override;
  explicit PROTOBUF_CONSTEXPR CameraStatusUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CameraStatusUpdate(const CameraStatusUpdate& from);
  CameraStatusUpdate(CameraStatusUpdate&& from) noexcept
    : CameraStatusUpdate() {
    *this = ::std::move(from);
  }

  inline CameraStatusUpdate& operator=(const CameraStatusUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline CameraStatusUpdate& operator=(CameraStatusUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CameraStatusUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const CameraStatusUpdate* internal_default_instance() {
    return reinterpret_cast<const CameraStatusUpdate*>(
               &_CameraStatusUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CameraStatusUpdate& a, CameraStatusUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(CameraStatusUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CameraStatusUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CameraStatusUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CameraStatusUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CameraStatusUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CameraStatusUpdate& from) {
    CameraStatusUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CameraStatusUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DepthCameras.CameraStatusUpdate";
  }
  protected:
  explicit CameraStatusUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandIdFieldNumber = 3,
    kCameraNameFieldNumber = 4,
    kCameraSerialFieldNumber = 5,
    kMsgTypeFieldNumber = 1,
    kStatusCodeFieldNumber = 6,
  };
  // string command_id = 3;
  void clear_command_id();
  const std::string& command_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command_id();
  PROTOBUF_NODISCARD std::string* release_command_id();
  void set_allocated_command_id(std::string* command_id);
  private:
  const std::string& _internal_command_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command_id(const std::string& value);
  std::string* _internal_mutable_command_id();
  public:

  // string camera_name = 4;
  void clear_camera_name();
  const std::string& camera_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_camera_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_camera_name();
  PROTOBUF_NODISCARD std::string* release_camera_name();
  void set_allocated_camera_name(std::string* camera_name);
  private:
  const std::string& _internal_camera_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_camera_name(const std::string& value);
  std::string* _internal_mutable_camera_name();
  public:

  // string camera_serial = 5;
  void clear_camera_serial();
  const std::string& camera_serial() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_camera_serial(ArgT0&& arg0, ArgT... args);
  std::string* mutable_camera_serial();
  PROTOBUF_NODISCARD std::string* release_camera_serial();
  void set_allocated_camera_serial(std::string* camera_serial);
  private:
  const std::string& _internal_camera_serial() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_camera_serial(const std::string& value);
  std::string* _internal_mutable_camera_serial();
  public:

  // .DepthCameras.MessageType msg_type = 1;
  void clear_msg_type();
  ::DepthCameras::MessageType msg_type() const;
  void set_msg_type(::DepthCameras::MessageType value);
  private:
  ::DepthCameras::MessageType _internal_msg_type() const;
  void _internal_set_msg_type(::DepthCameras::MessageType value);
  public:

  // .DepthCameras.DcCameraStatusCodes status_code = 6;
  void clear_status_code();
  ::DepthCameras::DcCameraStatusCodes status_code() const;
  void set_status_code(::DepthCameras::DcCameraStatusCodes value);
  private:
  ::DepthCameras::DcCameraStatusCodes _internal_status_code() const;
  void _internal_set_status_code(::DepthCameras::DcCameraStatusCodes value);
  public:

  // @@protoc_insertion_point(class_scope:DepthCameras.CameraStatusUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr camera_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr camera_serial_;
    int msg_type_;
    int status_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_depthCams_2eproto;
};
// -------------------------------------------------------------------

class DcRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DepthCameras.DcRequest) */ {
 public:
  inline DcRequest() : DcRequest(nullptr) {}
  ~DcRequest() override;
  explicit PROTOBUF_CONSTEXPR DcRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DcRequest(const DcRequest& from);
  DcRequest(DcRequest&& from) noexcept
    : DcRequest() {
    *this = ::std::move(from);
  }

  inline DcRequest& operator=(const DcRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DcRequest& operator=(DcRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DcRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DcRequest* internal_default_instance() {
    return reinterpret_cast<const DcRequest*>(
               &_DcRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DcRequest& a, DcRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DcRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DcRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DcRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DcRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DcRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DcRequest& from) {
    DcRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DcRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DepthCameras.DcRequest";
  }
  protected:
  explicit DcRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandIdFieldNumber = 1,
    kMessageDataFieldNumber = 5,
    kDcCmdTypeFieldNumber = 2,
    kTypeFieldNumber = 3,
    kMessageSizeFieldNumber = 4,
    kIsAcknowledgeFieldNumber = 6,
  };
  // string command_id = 1;
  void clear_command_id();
  const std::string& command_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command_id();
  PROTOBUF_NODISCARD std::string* release_command_id();
  void set_allocated_command_id(std::string* command_id);
  private:
  const std::string& _internal_command_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command_id(const std::string& value);
  std::string* _internal_mutable_command_id();
  public:

  // bytes message_data = 5;
  void clear_message_data();
  const std::string& message_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message_data();
  PROTOBUF_NODISCARD std::string* release_message_data();
  void set_allocated_message_data(std::string* message_data);
  private:
  const std::string& _internal_message_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message_data(const std::string& value);
  std::string* _internal_mutable_message_data();
  public:

  // .DepthCameras.DcCommandType dc_cmd_type = 2;
  void clear_dc_cmd_type();
  ::DepthCameras::DcCommandType dc_cmd_type() const;
  void set_dc_cmd_type(::DepthCameras::DcCommandType value);
  private:
  ::DepthCameras::DcCommandType _internal_dc_cmd_type() const;
  void _internal_set_dc_cmd_type(::DepthCameras::DcCommandType value);
  public:

  // .DepthCameras.MessageType type = 3;
  void clear_type();
  ::DepthCameras::MessageType type() const;
  void set_type(::DepthCameras::MessageType value);
  private:
  ::DepthCameras::MessageType _internal_type() const;
  void _internal_set_type(::DepthCameras::MessageType value);
  public:

  // int32 message_size = 4;
  void clear_message_size();
  int32_t message_size() const;
  void set_message_size(int32_t value);
  private:
  int32_t _internal_message_size() const;
  void _internal_set_message_size(int32_t value);
  public:

  // bool is_acknowledge = 6;
  void clear_is_acknowledge();
  bool is_acknowledge() const;
  void set_is_acknowledge(bool value);
  private:
  bool _internal_is_acknowledge() const;
  void _internal_set_is_acknowledge(bool value);
  public:

  // @@protoc_insertion_point(class_scope:DepthCameras.DcRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_data_;
    int dc_cmd_type_;
    int type_;
    int32_t message_size_;
    bool is_acknowledge_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_depthCams_2eproto;
};
// -------------------------------------------------------------------

class DcResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DepthCameras.DcResponse) */ {
 public:
  inline DcResponse() : DcResponse(nullptr) {}
  ~DcResponse() override;
  explicit PROTOBUF_CONSTEXPR DcResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DcResponse(const DcResponse& from);
  DcResponse(DcResponse&& from) noexcept
    : DcResponse() {
    *this = ::std::move(from);
  }

  inline DcResponse& operator=(const DcResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DcResponse& operator=(DcResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DcResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const DcResponse* internal_default_instance() {
    return reinterpret_cast<const DcResponse*>(
               &_DcResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(DcResponse& a, DcResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DcResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DcResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DcResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DcResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DcResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DcResponse& from) {
    DcResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DcResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DepthCameras.DcResponse";
  }
  protected:
  explicit DcResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommandIdFieldNumber = 1,
    kMessageDataFieldNumber = 5,
    kDcCmdTypeFieldNumber = 2,
    kTypeFieldNumber = 3,
    kMessageSizeFieldNumber = 4,
    kIsAcknowledgeFieldNumber = 6,
  };
  // string command_id = 1;
  void clear_command_id();
  const std::string& command_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_command_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_command_id();
  PROTOBUF_NODISCARD std::string* release_command_id();
  void set_allocated_command_id(std::string* command_id);
  private:
  const std::string& _internal_command_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_command_id(const std::string& value);
  std::string* _internal_mutable_command_id();
  public:

  // bytes message_data = 5;
  void clear_message_data();
  const std::string& message_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message_data();
  PROTOBUF_NODISCARD std::string* release_message_data();
  void set_allocated_message_data(std::string* message_data);
  private:
  const std::string& _internal_message_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message_data(const std::string& value);
  std::string* _internal_mutable_message_data();
  public:

  // .DepthCameras.DcCommandType dc_cmd_type = 2;
  void clear_dc_cmd_type();
  ::DepthCameras::DcCommandType dc_cmd_type() const;
  void set_dc_cmd_type(::DepthCameras::DcCommandType value);
  private:
  ::DepthCameras::DcCommandType _internal_dc_cmd_type() const;
  void _internal_set_dc_cmd_type(::DepthCameras::DcCommandType value);
  public:

  // .DepthCameras.MessageType type = 3;
  void clear_type();
  ::DepthCameras::MessageType type() const;
  void set_type(::DepthCameras::MessageType value);
  private:
  ::DepthCameras::MessageType _internal_type() const;
  void _internal_set_type(::DepthCameras::MessageType value);
  public:

  // int32 message_size = 4;
  void clear_message_size();
  int32_t message_size() const;
  void set_message_size(int32_t value);
  private:
  int32_t _internal_message_size() const;
  void _internal_set_message_size(int32_t value);
  public:

  // bool is_acknowledge = 6;
  void clear_is_acknowledge();
  bool is_acknowledge() const;
  void set_is_acknowledge(bool value);
  private:
  bool _internal_is_acknowledge() const;
  void _internal_set_is_acknowledge(bool value);
  public:

  // @@protoc_insertion_point(class_scope:DepthCameras.DcResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr command_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_data_;
    int dc_cmd_type_;
    int type_;
    int32_t message_size_;
    bool is_acknowledge_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_depthCams_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Acknowledge

// .DepthCameras.MessageType type = 1;
inline void Acknowledge::clear_type() {
  _impl_.type_ = 0;
}
inline ::DepthCameras::MessageType Acknowledge::_internal_type() const {
  return static_cast< ::DepthCameras::MessageType >(_impl_.type_);
}
inline ::DepthCameras::MessageType Acknowledge::type() const {
  // @@protoc_insertion_point(field_get:DepthCameras.Acknowledge.type)
  return _internal_type();
}
inline void Acknowledge::_internal_set_type(::DepthCameras::MessageType value) {
  
  _impl_.type_ = value;
}
inline void Acknowledge::set_type(::DepthCameras::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:DepthCameras.Acknowledge.type)
}

// string command_id = 2;
inline void Acknowledge::clear_command_id() {
  _impl_.command_id_.ClearToEmpty();
}
inline const std::string& Acknowledge::command_id() const {
  // @@protoc_insertion_point(field_get:DepthCameras.Acknowledge.command_id)
  return _internal_command_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Acknowledge::set_command_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DepthCameras.Acknowledge.command_id)
}
inline std::string* Acknowledge::mutable_command_id() {
  std::string* _s = _internal_mutable_command_id();
  // @@protoc_insertion_point(field_mutable:DepthCameras.Acknowledge.command_id)
  return _s;
}
inline const std::string& Acknowledge::_internal_command_id() const {
  return _impl_.command_id_.Get();
}
inline void Acknowledge::_internal_set_command_id(const std::string& value) {
  
  _impl_.command_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Acknowledge::_internal_mutable_command_id() {
  
  return _impl_.command_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Acknowledge::release_command_id() {
  // @@protoc_insertion_point(field_release:DepthCameras.Acknowledge.command_id)
  return _impl_.command_id_.Release();
}
inline void Acknowledge::set_allocated_command_id(std::string* command_id) {
  if (command_id != nullptr) {
    
  } else {
    
  }
  _impl_.command_id_.SetAllocated(command_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_id_.IsDefault()) {
    _impl_.command_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DepthCameras.Acknowledge.command_id)
}

// .DepthCameras.MessageType acknowledged_type = 3;
inline void Acknowledge::clear_acknowledged_type() {
  _impl_.acknowledged_type_ = 0;
}
inline ::DepthCameras::MessageType Acknowledge::_internal_acknowledged_type() const {
  return static_cast< ::DepthCameras::MessageType >(_impl_.acknowledged_type_);
}
inline ::DepthCameras::MessageType Acknowledge::acknowledged_type() const {
  // @@protoc_insertion_point(field_get:DepthCameras.Acknowledge.acknowledged_type)
  return _internal_acknowledged_type();
}
inline void Acknowledge::_internal_set_acknowledged_type(::DepthCameras::MessageType value) {
  
  _impl_.acknowledged_type_ = value;
}
inline void Acknowledge::set_acknowledged_type(::DepthCameras::MessageType value) {
  _internal_set_acknowledged_type(value);
  // @@protoc_insertion_point(field_set:DepthCameras.Acknowledge.acknowledged_type)
}

// -------------------------------------------------------------------

// CommandStatusUpdate

// .DepthCameras.MessageType msg_type = 1;
inline void CommandStatusUpdate::clear_msg_type() {
  _impl_.msg_type_ = 0;
}
inline ::DepthCameras::MessageType CommandStatusUpdate::_internal_msg_type() const {
  return static_cast< ::DepthCameras::MessageType >(_impl_.msg_type_);
}
inline ::DepthCameras::MessageType CommandStatusUpdate::msg_type() const {
  // @@protoc_insertion_point(field_get:DepthCameras.CommandStatusUpdate.msg_type)
  return _internal_msg_type();
}
inline void CommandStatusUpdate::_internal_set_msg_type(::DepthCameras::MessageType value) {
  
  _impl_.msg_type_ = value;
}
inline void CommandStatusUpdate::set_msg_type(::DepthCameras::MessageType value) {
  _internal_set_msg_type(value);
  // @@protoc_insertion_point(field_set:DepthCameras.CommandStatusUpdate.msg_type)
}

// string command_id = 2;
inline void CommandStatusUpdate::clear_command_id() {
  _impl_.command_id_.ClearToEmpty();
}
inline const std::string& CommandStatusUpdate::command_id() const {
  // @@protoc_insertion_point(field_get:DepthCameras.CommandStatusUpdate.command_id)
  return _internal_command_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CommandStatusUpdate::set_command_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DepthCameras.CommandStatusUpdate.command_id)
}
inline std::string* CommandStatusUpdate::mutable_command_id() {
  std::string* _s = _internal_mutable_command_id();
  // @@protoc_insertion_point(field_mutable:DepthCameras.CommandStatusUpdate.command_id)
  return _s;
}
inline const std::string& CommandStatusUpdate::_internal_command_id() const {
  return _impl_.command_id_.Get();
}
inline void CommandStatusUpdate::_internal_set_command_id(const std::string& value) {
  
  _impl_.command_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CommandStatusUpdate::_internal_mutable_command_id() {
  
  return _impl_.command_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CommandStatusUpdate::release_command_id() {
  // @@protoc_insertion_point(field_release:DepthCameras.CommandStatusUpdate.command_id)
  return _impl_.command_id_.Release();
}
inline void CommandStatusUpdate::set_allocated_command_id(std::string* command_id) {
  if (command_id != nullptr) {
    
  } else {
    
  }
  _impl_.command_id_.SetAllocated(command_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_id_.IsDefault()) {
    _impl_.command_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DepthCameras.CommandStatusUpdate.command_id)
}

// int32 status_code = 3;
inline void CommandStatusUpdate::clear_status_code() {
  _impl_.status_code_ = 0;
}
inline int32_t CommandStatusUpdate::_internal_status_code() const {
  return _impl_.status_code_;
}
inline int32_t CommandStatusUpdate::status_code() const {
  // @@protoc_insertion_point(field_get:DepthCameras.CommandStatusUpdate.status_code)
  return _internal_status_code();
}
inline void CommandStatusUpdate::_internal_set_status_code(int32_t value) {
  
  _impl_.status_code_ = value;
}
inline void CommandStatusUpdate::set_status_code(int32_t value) {
  _internal_set_status_code(value);
  // @@protoc_insertion_point(field_set:DepthCameras.CommandStatusUpdate.status_code)
}

// -------------------------------------------------------------------

// CameraStatusUpdate

// .DepthCameras.MessageType msg_type = 1;
inline void CameraStatusUpdate::clear_msg_type() {
  _impl_.msg_type_ = 0;
}
inline ::DepthCameras::MessageType CameraStatusUpdate::_internal_msg_type() const {
  return static_cast< ::DepthCameras::MessageType >(_impl_.msg_type_);
}
inline ::DepthCameras::MessageType CameraStatusUpdate::msg_type() const {
  // @@protoc_insertion_point(field_get:DepthCameras.CameraStatusUpdate.msg_type)
  return _internal_msg_type();
}
inline void CameraStatusUpdate::_internal_set_msg_type(::DepthCameras::MessageType value) {
  
  _impl_.msg_type_ = value;
}
inline void CameraStatusUpdate::set_msg_type(::DepthCameras::MessageType value) {
  _internal_set_msg_type(value);
  // @@protoc_insertion_point(field_set:DepthCameras.CameraStatusUpdate.msg_type)
}

// string command_id = 3;
inline void CameraStatusUpdate::clear_command_id() {
  _impl_.command_id_.ClearToEmpty();
}
inline const std::string& CameraStatusUpdate::command_id() const {
  // @@protoc_insertion_point(field_get:DepthCameras.CameraStatusUpdate.command_id)
  return _internal_command_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CameraStatusUpdate::set_command_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DepthCameras.CameraStatusUpdate.command_id)
}
inline std::string* CameraStatusUpdate::mutable_command_id() {
  std::string* _s = _internal_mutable_command_id();
  // @@protoc_insertion_point(field_mutable:DepthCameras.CameraStatusUpdate.command_id)
  return _s;
}
inline const std::string& CameraStatusUpdate::_internal_command_id() const {
  return _impl_.command_id_.Get();
}
inline void CameraStatusUpdate::_internal_set_command_id(const std::string& value) {
  
  _impl_.command_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CameraStatusUpdate::_internal_mutable_command_id() {
  
  return _impl_.command_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CameraStatusUpdate::release_command_id() {
  // @@protoc_insertion_point(field_release:DepthCameras.CameraStatusUpdate.command_id)
  return _impl_.command_id_.Release();
}
inline void CameraStatusUpdate::set_allocated_command_id(std::string* command_id) {
  if (command_id != nullptr) {
    
  } else {
    
  }
  _impl_.command_id_.SetAllocated(command_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_id_.IsDefault()) {
    _impl_.command_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DepthCameras.CameraStatusUpdate.command_id)
}

// string camera_name = 4;
inline void CameraStatusUpdate::clear_camera_name() {
  _impl_.camera_name_.ClearToEmpty();
}
inline const std::string& CameraStatusUpdate::camera_name() const {
  // @@protoc_insertion_point(field_get:DepthCameras.CameraStatusUpdate.camera_name)
  return _internal_camera_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CameraStatusUpdate::set_camera_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.camera_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DepthCameras.CameraStatusUpdate.camera_name)
}
inline std::string* CameraStatusUpdate::mutable_camera_name() {
  std::string* _s = _internal_mutable_camera_name();
  // @@protoc_insertion_point(field_mutable:DepthCameras.CameraStatusUpdate.camera_name)
  return _s;
}
inline const std::string& CameraStatusUpdate::_internal_camera_name() const {
  return _impl_.camera_name_.Get();
}
inline void CameraStatusUpdate::_internal_set_camera_name(const std::string& value) {
  
  _impl_.camera_name_.Set(value, GetArenaForAllocation());
}
inline std::string* CameraStatusUpdate::_internal_mutable_camera_name() {
  
  return _impl_.camera_name_.Mutable(GetArenaForAllocation());
}
inline std::string* CameraStatusUpdate::release_camera_name() {
  // @@protoc_insertion_point(field_release:DepthCameras.CameraStatusUpdate.camera_name)
  return _impl_.camera_name_.Release();
}
inline void CameraStatusUpdate::set_allocated_camera_name(std::string* camera_name) {
  if (camera_name != nullptr) {
    
  } else {
    
  }
  _impl_.camera_name_.SetAllocated(camera_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.camera_name_.IsDefault()) {
    _impl_.camera_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DepthCameras.CameraStatusUpdate.camera_name)
}

// string camera_serial = 5;
inline void CameraStatusUpdate::clear_camera_serial() {
  _impl_.camera_serial_.ClearToEmpty();
}
inline const std::string& CameraStatusUpdate::camera_serial() const {
  // @@protoc_insertion_point(field_get:DepthCameras.CameraStatusUpdate.camera_serial)
  return _internal_camera_serial();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CameraStatusUpdate::set_camera_serial(ArgT0&& arg0, ArgT... args) {
 
 _impl_.camera_serial_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DepthCameras.CameraStatusUpdate.camera_serial)
}
inline std::string* CameraStatusUpdate::mutable_camera_serial() {
  std::string* _s = _internal_mutable_camera_serial();
  // @@protoc_insertion_point(field_mutable:DepthCameras.CameraStatusUpdate.camera_serial)
  return _s;
}
inline const std::string& CameraStatusUpdate::_internal_camera_serial() const {
  return _impl_.camera_serial_.Get();
}
inline void CameraStatusUpdate::_internal_set_camera_serial(const std::string& value) {
  
  _impl_.camera_serial_.Set(value, GetArenaForAllocation());
}
inline std::string* CameraStatusUpdate::_internal_mutable_camera_serial() {
  
  return _impl_.camera_serial_.Mutable(GetArenaForAllocation());
}
inline std::string* CameraStatusUpdate::release_camera_serial() {
  // @@protoc_insertion_point(field_release:DepthCameras.CameraStatusUpdate.camera_serial)
  return _impl_.camera_serial_.Release();
}
inline void CameraStatusUpdate::set_allocated_camera_serial(std::string* camera_serial) {
  if (camera_serial != nullptr) {
    
  } else {
    
  }
  _impl_.camera_serial_.SetAllocated(camera_serial, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.camera_serial_.IsDefault()) {
    _impl_.camera_serial_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DepthCameras.CameraStatusUpdate.camera_serial)
}

// .DepthCameras.DcCameraStatusCodes status_code = 6;
inline void CameraStatusUpdate::clear_status_code() {
  _impl_.status_code_ = 0;
}
inline ::DepthCameras::DcCameraStatusCodes CameraStatusUpdate::_internal_status_code() const {
  return static_cast< ::DepthCameras::DcCameraStatusCodes >(_impl_.status_code_);
}
inline ::DepthCameras::DcCameraStatusCodes CameraStatusUpdate::status_code() const {
  // @@protoc_insertion_point(field_get:DepthCameras.CameraStatusUpdate.status_code)
  return _internal_status_code();
}
inline void CameraStatusUpdate::_internal_set_status_code(::DepthCameras::DcCameraStatusCodes value) {
  
  _impl_.status_code_ = value;
}
inline void CameraStatusUpdate::set_status_code(::DepthCameras::DcCameraStatusCodes value) {
  _internal_set_status_code(value);
  // @@protoc_insertion_point(field_set:DepthCameras.CameraStatusUpdate.status_code)
}

// -------------------------------------------------------------------

// DcRequest

// string command_id = 1;
inline void DcRequest::clear_command_id() {
  _impl_.command_id_.ClearToEmpty();
}
inline const std::string& DcRequest::command_id() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcRequest.command_id)
  return _internal_command_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DcRequest::set_command_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DepthCameras.DcRequest.command_id)
}
inline std::string* DcRequest::mutable_command_id() {
  std::string* _s = _internal_mutable_command_id();
  // @@protoc_insertion_point(field_mutable:DepthCameras.DcRequest.command_id)
  return _s;
}
inline const std::string& DcRequest::_internal_command_id() const {
  return _impl_.command_id_.Get();
}
inline void DcRequest::_internal_set_command_id(const std::string& value) {
  
  _impl_.command_id_.Set(value, GetArenaForAllocation());
}
inline std::string* DcRequest::_internal_mutable_command_id() {
  
  return _impl_.command_id_.Mutable(GetArenaForAllocation());
}
inline std::string* DcRequest::release_command_id() {
  // @@protoc_insertion_point(field_release:DepthCameras.DcRequest.command_id)
  return _impl_.command_id_.Release();
}
inline void DcRequest::set_allocated_command_id(std::string* command_id) {
  if (command_id != nullptr) {
    
  } else {
    
  }
  _impl_.command_id_.SetAllocated(command_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_id_.IsDefault()) {
    _impl_.command_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DepthCameras.DcRequest.command_id)
}

// .DepthCameras.DcCommandType dc_cmd_type = 2;
inline void DcRequest::clear_dc_cmd_type() {
  _impl_.dc_cmd_type_ = 0;
}
inline ::DepthCameras::DcCommandType DcRequest::_internal_dc_cmd_type() const {
  return static_cast< ::DepthCameras::DcCommandType >(_impl_.dc_cmd_type_);
}
inline ::DepthCameras::DcCommandType DcRequest::dc_cmd_type() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcRequest.dc_cmd_type)
  return _internal_dc_cmd_type();
}
inline void DcRequest::_internal_set_dc_cmd_type(::DepthCameras::DcCommandType value) {
  
  _impl_.dc_cmd_type_ = value;
}
inline void DcRequest::set_dc_cmd_type(::DepthCameras::DcCommandType value) {
  _internal_set_dc_cmd_type(value);
  // @@protoc_insertion_point(field_set:DepthCameras.DcRequest.dc_cmd_type)
}

// .DepthCameras.MessageType type = 3;
inline void DcRequest::clear_type() {
  _impl_.type_ = 0;
}
inline ::DepthCameras::MessageType DcRequest::_internal_type() const {
  return static_cast< ::DepthCameras::MessageType >(_impl_.type_);
}
inline ::DepthCameras::MessageType DcRequest::type() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcRequest.type)
  return _internal_type();
}
inline void DcRequest::_internal_set_type(::DepthCameras::MessageType value) {
  
  _impl_.type_ = value;
}
inline void DcRequest::set_type(::DepthCameras::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:DepthCameras.DcRequest.type)
}

// int32 message_size = 4;
inline void DcRequest::clear_message_size() {
  _impl_.message_size_ = 0;
}
inline int32_t DcRequest::_internal_message_size() const {
  return _impl_.message_size_;
}
inline int32_t DcRequest::message_size() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcRequest.message_size)
  return _internal_message_size();
}
inline void DcRequest::_internal_set_message_size(int32_t value) {
  
  _impl_.message_size_ = value;
}
inline void DcRequest::set_message_size(int32_t value) {
  _internal_set_message_size(value);
  // @@protoc_insertion_point(field_set:DepthCameras.DcRequest.message_size)
}

// bytes message_data = 5;
inline void DcRequest::clear_message_data() {
  _impl_.message_data_.ClearToEmpty();
}
inline const std::string& DcRequest::message_data() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcRequest.message_data)
  return _internal_message_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DcRequest::set_message_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DepthCameras.DcRequest.message_data)
}
inline std::string* DcRequest::mutable_message_data() {
  std::string* _s = _internal_mutable_message_data();
  // @@protoc_insertion_point(field_mutable:DepthCameras.DcRequest.message_data)
  return _s;
}
inline const std::string& DcRequest::_internal_message_data() const {
  return _impl_.message_data_.Get();
}
inline void DcRequest::_internal_set_message_data(const std::string& value) {
  
  _impl_.message_data_.Set(value, GetArenaForAllocation());
}
inline std::string* DcRequest::_internal_mutable_message_data() {
  
  return _impl_.message_data_.Mutable(GetArenaForAllocation());
}
inline std::string* DcRequest::release_message_data() {
  // @@protoc_insertion_point(field_release:DepthCameras.DcRequest.message_data)
  return _impl_.message_data_.Release();
}
inline void DcRequest::set_allocated_message_data(std::string* message_data) {
  if (message_data != nullptr) {
    
  } else {
    
  }
  _impl_.message_data_.SetAllocated(message_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_data_.IsDefault()) {
    _impl_.message_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DepthCameras.DcRequest.message_data)
}

// bool is_acknowledge = 6;
inline void DcRequest::clear_is_acknowledge() {
  _impl_.is_acknowledge_ = false;
}
inline bool DcRequest::_internal_is_acknowledge() const {
  return _impl_.is_acknowledge_;
}
inline bool DcRequest::is_acknowledge() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcRequest.is_acknowledge)
  return _internal_is_acknowledge();
}
inline void DcRequest::_internal_set_is_acknowledge(bool value) {
  
  _impl_.is_acknowledge_ = value;
}
inline void DcRequest::set_is_acknowledge(bool value) {
  _internal_set_is_acknowledge(value);
  // @@protoc_insertion_point(field_set:DepthCameras.DcRequest.is_acknowledge)
}

// -------------------------------------------------------------------

// DcResponse

// string command_id = 1;
inline void DcResponse::clear_command_id() {
  _impl_.command_id_.ClearToEmpty();
}
inline const std::string& DcResponse::command_id() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcResponse.command_id)
  return _internal_command_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DcResponse::set_command_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.command_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DepthCameras.DcResponse.command_id)
}
inline std::string* DcResponse::mutable_command_id() {
  std::string* _s = _internal_mutable_command_id();
  // @@protoc_insertion_point(field_mutable:DepthCameras.DcResponse.command_id)
  return _s;
}
inline const std::string& DcResponse::_internal_command_id() const {
  return _impl_.command_id_.Get();
}
inline void DcResponse::_internal_set_command_id(const std::string& value) {
  
  _impl_.command_id_.Set(value, GetArenaForAllocation());
}
inline std::string* DcResponse::_internal_mutable_command_id() {
  
  return _impl_.command_id_.Mutable(GetArenaForAllocation());
}
inline std::string* DcResponse::release_command_id() {
  // @@protoc_insertion_point(field_release:DepthCameras.DcResponse.command_id)
  return _impl_.command_id_.Release();
}
inline void DcResponse::set_allocated_command_id(std::string* command_id) {
  if (command_id != nullptr) {
    
  } else {
    
  }
  _impl_.command_id_.SetAllocated(command_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.command_id_.IsDefault()) {
    _impl_.command_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DepthCameras.DcResponse.command_id)
}

// .DepthCameras.DcCommandType dc_cmd_type = 2;
inline void DcResponse::clear_dc_cmd_type() {
  _impl_.dc_cmd_type_ = 0;
}
inline ::DepthCameras::DcCommandType DcResponse::_internal_dc_cmd_type() const {
  return static_cast< ::DepthCameras::DcCommandType >(_impl_.dc_cmd_type_);
}
inline ::DepthCameras::DcCommandType DcResponse::dc_cmd_type() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcResponse.dc_cmd_type)
  return _internal_dc_cmd_type();
}
inline void DcResponse::_internal_set_dc_cmd_type(::DepthCameras::DcCommandType value) {
  
  _impl_.dc_cmd_type_ = value;
}
inline void DcResponse::set_dc_cmd_type(::DepthCameras::DcCommandType value) {
  _internal_set_dc_cmd_type(value);
  // @@protoc_insertion_point(field_set:DepthCameras.DcResponse.dc_cmd_type)
}

// .DepthCameras.MessageType type = 3;
inline void DcResponse::clear_type() {
  _impl_.type_ = 0;
}
inline ::DepthCameras::MessageType DcResponse::_internal_type() const {
  return static_cast< ::DepthCameras::MessageType >(_impl_.type_);
}
inline ::DepthCameras::MessageType DcResponse::type() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcResponse.type)
  return _internal_type();
}
inline void DcResponse::_internal_set_type(::DepthCameras::MessageType value) {
  
  _impl_.type_ = value;
}
inline void DcResponse::set_type(::DepthCameras::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:DepthCameras.DcResponse.type)
}

// int32 message_size = 4;
inline void DcResponse::clear_message_size() {
  _impl_.message_size_ = 0;
}
inline int32_t DcResponse::_internal_message_size() const {
  return _impl_.message_size_;
}
inline int32_t DcResponse::message_size() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcResponse.message_size)
  return _internal_message_size();
}
inline void DcResponse::_internal_set_message_size(int32_t value) {
  
  _impl_.message_size_ = value;
}
inline void DcResponse::set_message_size(int32_t value) {
  _internal_set_message_size(value);
  // @@protoc_insertion_point(field_set:DepthCameras.DcResponse.message_size)
}

// bytes message_data = 5;
inline void DcResponse::clear_message_data() {
  _impl_.message_data_.ClearToEmpty();
}
inline const std::string& DcResponse::message_data() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcResponse.message_data)
  return _internal_message_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DcResponse::set_message_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DepthCameras.DcResponse.message_data)
}
inline std::string* DcResponse::mutable_message_data() {
  std::string* _s = _internal_mutable_message_data();
  // @@protoc_insertion_point(field_mutable:DepthCameras.DcResponse.message_data)
  return _s;
}
inline const std::string& DcResponse::_internal_message_data() const {
  return _impl_.message_data_.Get();
}
inline void DcResponse::_internal_set_message_data(const std::string& value) {
  
  _impl_.message_data_.Set(value, GetArenaForAllocation());
}
inline std::string* DcResponse::_internal_mutable_message_data() {
  
  return _impl_.message_data_.Mutable(GetArenaForAllocation());
}
inline std::string* DcResponse::release_message_data() {
  // @@protoc_insertion_point(field_release:DepthCameras.DcResponse.message_data)
  return _impl_.message_data_.Release();
}
inline void DcResponse::set_allocated_message_data(std::string* message_data) {
  if (message_data != nullptr) {
    
  } else {
    
  }
  _impl_.message_data_.SetAllocated(message_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_data_.IsDefault()) {
    _impl_.message_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DepthCameras.DcResponse.message_data)
}

// bool is_acknowledge = 6;
inline void DcResponse::clear_is_acknowledge() {
  _impl_.is_acknowledge_ = false;
}
inline bool DcResponse::_internal_is_acknowledge() const {
  return _impl_.is_acknowledge_;
}
inline bool DcResponse::is_acknowledge() const {
  // @@protoc_insertion_point(field_get:DepthCameras.DcResponse.is_acknowledge)
  return _internal_is_acknowledge();
}
inline void DcResponse::_internal_set_is_acknowledge(bool value) {
  
  _impl_.is_acknowledge_ = value;
}
inline void DcResponse::set_is_acknowledge(bool value) {
  _internal_set_is_acknowledge(value);
  // @@protoc_insertion_point(field_set:DepthCameras.DcResponse.is_acknowledge)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace DepthCameras

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::DepthCameras::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DepthCameras::MessageType>() {
  return ::DepthCameras::MessageType_descriptor();
}
template <> struct is_proto_enum< ::DepthCameras::DcCommandType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DepthCameras::DcCommandType>() {
  return ::DepthCameras::DcCommandType_descriptor();
}
template <> struct is_proto_enum< ::DepthCameras::DcCameraStatusCodes> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DepthCameras::DcCameraStatusCodes>() {
  return ::DepthCameras::DcCameraStatusCodes_descriptor();
}
template <> struct is_proto_enum< ::DepthCameras::DcStatusCodes> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DepthCameras::DcStatusCodes>() {
  return ::DepthCameras::DcStatusCodes_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_depthCams_2eproto
