// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: depthCams.proto
#ifndef GRPC_depthCams_2eproto__INCLUDED
#define GRPC_depthCams_2eproto__INCLUDED

#include "depthCams.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace DepthCameras {

class DcApiService final {
 public:
  static constexpr char const* service_full_name() {
    return "DepthCameras.DcApiService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>> DcApi(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>>(DcApiRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>> AsyncDcApi(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>>(AsyncDcApiRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>> PrepareAsyncDcApi(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>>(PrepareAsyncDcApiRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DcApi(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::DepthCameras::DcRequest,::DepthCameras::DcResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* DcApiRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* AsyncDcApiRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* PrepareAsyncDcApiRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>> DcApi(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>>(DcApiRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>> AsyncDcApi(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>>(AsyncDcApiRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>> PrepareAsyncDcApi(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>>(PrepareAsyncDcApiRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DcApi(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::DepthCameras::DcRequest,::DepthCameras::DcResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* DcApiRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* AsyncDcApiRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* PrepareAsyncDcApiRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DcApi_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DcApi(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::DepthCameras::DcResponse, ::DepthCameras::DcRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_DcApi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DcApi() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DcApi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DcApi(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::DepthCameras::DcResponse, ::DepthCameras::DcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDcApi(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::DepthCameras::DcResponse, ::DepthCameras::DcRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DcApi<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DcApi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DcApi() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DcApi(context); }));
    }
    ~WithCallbackMethod_DcApi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DcApi(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::DepthCameras::DcResponse, ::DepthCameras::DcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* DcApi(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_DcApi<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DcApi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DcApi() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DcApi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DcApi(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::DepthCameras::DcResponse, ::DepthCameras::DcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DcApi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DcApi() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DcApi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DcApi(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::DepthCameras::DcResponse, ::DepthCameras::DcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDcApi(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DcApi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DcApi() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->DcApi(context); }));
    }
    ~WithRawCallbackMethod_DcApi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DcApi(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::DepthCameras::DcResponse, ::DepthCameras::DcRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* DcApi(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace DepthCameras


#endif  // GRPC_depthCams_2eproto__INCLUDED
