// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: depthCams.proto

#include "Fulfil.CPPUtils/comm/depthCams.pb.h"
#include "Fulfil.CPPUtils/comm/depthCams.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace DepthCameras {

static const char* DcApiService_method_names[] = {
  "/DepthCameras.DcApiService/DcApi",
};

std::unique_ptr< DcApiService::Stub> DcApiService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DcApiService::Stub> stub(new DcApiService::Stub(channel, options));
  return stub;
}

DcApiService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_DcApi_(DcApiService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* DcApiService::Stub::DcApiRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>::Create(channel_.get(), rpcmethod_DcApi_, context);
}

void DcApiService::Stub::async::DcApi(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::DepthCameras::DcRequest,::DepthCameras::DcResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::DepthCameras::DcRequest,::DepthCameras::DcResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_DcApi_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* DcApiService::Stub::AsyncDcApiRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>::Create(channel_.get(), cq, rpcmethod_DcApi_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>* DcApiService::Stub::PrepareAsyncDcApiRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>::Create(channel_.get(), cq, rpcmethod_DcApi_, context, false, nullptr);
}

DcApiService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DcApiService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< DcApiService::Service, ::DepthCameras::DcRequest, ::DepthCameras::DcResponse>(
          [](DcApiService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::DepthCameras::DcResponse,
             ::DepthCameras::DcRequest>* stream) {
               return service->DcApi(ctx, stream);
             }, this)));
}

DcApiService::Service::~Service() {
}

::grpc::Status DcApiService::Service::DcApi(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::DepthCameras::DcResponse, ::DepthCameras::DcRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace DepthCameras

