// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: depthCams.proto

#include "Fulfil.CPPUtils/comm/depthCams.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace DepthCameras {
PROTOBUF_CONSTEXPR Acknowledge::Acknowledge(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.command_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.acknowledged_type_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AcknowledgeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AcknowledgeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AcknowledgeDefaultTypeInternal() {}
  union {
    Acknowledge _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AcknowledgeDefaultTypeInternal _Acknowledge_default_instance_;
PROTOBUF_CONSTEXPR CommandStatusUpdate::CommandStatusUpdate(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.command_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.msg_type_)*/0
  , /*decltype(_impl_.status_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CommandStatusUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CommandStatusUpdateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CommandStatusUpdateDefaultTypeInternal() {}
  union {
    CommandStatusUpdate _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CommandStatusUpdateDefaultTypeInternal _CommandStatusUpdate_default_instance_;
PROTOBUF_CONSTEXPR DcRequest::DcRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.command_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dc_cmd_type_)*/0
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.message_size_)*/0
  , /*decltype(_impl_.is_acknowledge_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DcRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DcRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DcRequestDefaultTypeInternal() {}
  union {
    DcRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DcRequestDefaultTypeInternal _DcRequest_default_instance_;
PROTOBUF_CONSTEXPR DcResponse::DcResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.command_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dc_cmd_type_)*/0
  , /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.message_size_)*/0
  , /*decltype(_impl_.is_acknowledge_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DcResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DcResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DcResponseDefaultTypeInternal() {}
  union {
    DcResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DcResponseDefaultTypeInternal _DcResponse_default_instance_;
}  // namespace DepthCameras
static ::_pb::Metadata file_level_metadata_depthCams_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_depthCams_2eproto[3];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_depthCams_2eproto = nullptr;

const uint32_t TableStruct_depthCams_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DepthCameras::Acknowledge, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DepthCameras::Acknowledge, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::Acknowledge, _impl_.command_id_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::Acknowledge, _impl_.acknowledged_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DepthCameras::CommandStatusUpdate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DepthCameras::CommandStatusUpdate, _impl_.msg_type_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::CommandStatusUpdate, _impl_.command_id_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::CommandStatusUpdate, _impl_.status_code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcRequest, _impl_.command_id_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcRequest, _impl_.dc_cmd_type_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcRequest, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcRequest, _impl_.message_size_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcRequest, _impl_.message_data_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcRequest, _impl_.is_acknowledge_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcResponse, _impl_.command_id_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcResponse, _impl_.dc_cmd_type_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcResponse, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcResponse, _impl_.message_size_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcResponse, _impl_.message_data_),
  PROTOBUF_FIELD_OFFSET(::DepthCameras::DcResponse, _impl_.is_acknowledge_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::DepthCameras::Acknowledge)},
  { 9, -1, -1, sizeof(::DepthCameras::CommandStatusUpdate)},
  { 18, -1, -1, sizeof(::DepthCameras::DcRequest)},
  { 30, -1, -1, sizeof(::DepthCameras::DcResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::DepthCameras::_Acknowledge_default_instance_._instance,
  &::DepthCameras::_CommandStatusUpdate_default_instance_._instance,
  &::DepthCameras::_DcRequest_default_instance_._instance,
  &::DepthCameras::_DcResponse_default_instance_._instance,
};

const char descriptor_table_protodef_depthCams_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017depthCams.proto\022\014DepthCameras\"\200\001\n\013Ackn"
  "owledge\022\'\n\004type\030\001 \001(\0162\031.DepthCameras.Mes"
  "sageType\022\022\n\ncommand_id\030\002 \001(\t\0224\n\021acknowle"
  "dged_type\030\003 \001(\0162\031.DepthCameras.MessageTy"
  "pe\"k\n\023CommandStatusUpdate\022+\n\010msg_type\030\001 "
  "\001(\0162\031.DepthCameras.MessageType\022\022\n\ncomman"
  "d_id\030\002 \001(\t\022\023\n\013status_code\030\003 \001(\005\"\276\001\n\tDcRe"
  "quest\022\022\n\ncommand_id\030\001 \001(\t\0220\n\013dc_cmd_type"
  "\030\002 \001(\0162\033.DepthCameras.DcCommandType\022\'\n\004t"
  "ype\030\003 \001(\0162\031.DepthCameras.MessageType\022\024\n\014"
  "message_size\030\004 \001(\005\022\024\n\014message_data\030\005 \001(\014"
  "\022\026\n\016is_acknowledge\030\006 \001(\010\"\277\001\n\nDcResponse\022"
  "\022\n\ncommand_id\030\001 \001(\t\0220\n\013dc_cmd_type\030\002 \001(\016"
  "2\033.DepthCameras.DcCommandType\022\'\n\004type\030\003 "
  "\001(\0162\031.DepthCameras.MessageType\022\024\n\014messag"
  "e_size\030\004 \001(\005\022\024\n\014message_data\030\005 \001(\014\022\026\n\016is"
  "_acknowledge\030\006 \001(\010*\344\001\n\013MessageType\022\034\n\030ME"
  "SSAGE_TYPE_UNSPECIFIED\020\000\022\032\n\026MESSAGE_TYPE"
  "_ACK_REPLY\020\001\022\037\n\033MESSAGE_TYPE_COMMAND_STA"
  "TUS\020\002\022\036\n\032MESSAGE_TYPE_GENERIC_QUERY\020\003\022\032\n"
  "\026MESSAGE_TYPE_HEARTBEAT\020\004\022\"\n\036MESSAGE_TYP"
  "E_BAG_STATE_REQUEST\020\005\022\032\n\026MESSAGE_TYPE_BA"
  "G_STATE\020\006*]\n\rDcCommandType\022\032\n\026DC_COMMAND"
  "_UNSPECIFIED\020\000\022\022\n\016DC_COMMAND_NOP\020\001\022\034\n\030DC"
  "_COMMAND_GENERIC_QUERY\020\002*I\n\rDcStatusCode"
  "s\022\027\n\023STATUS_CODE_SUCCESS\020\000\022\037\n\022STATUS_COD"
  "E_FAILED\020\377\377\377\377\377\377\377\377\377\0012P\n\014DcApiService\022@\n\005D"
  "cApi\022\027.DepthCameras.DcRequest\032\030.DepthCam"
  "eras.DcResponse\"\000(\0010\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_depthCams_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_depthCams_2eproto = {
    false, false, 1149, descriptor_table_protodef_depthCams_2eproto,
    "depthCams.proto",
    &descriptor_table_depthCams_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_depthCams_2eproto::offsets,
    file_level_metadata_depthCams_2eproto, file_level_enum_descriptors_depthCams_2eproto,
    file_level_service_descriptors_depthCams_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_depthCams_2eproto_getter() {
  return &descriptor_table_depthCams_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_depthCams_2eproto(&descriptor_table_depthCams_2eproto);
namespace DepthCameras {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_depthCams_2eproto);
  return file_level_enum_descriptors_depthCams_2eproto[0];
}
bool MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DcCommandType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_depthCams_2eproto);
  return file_level_enum_descriptors_depthCams_2eproto[1];
}
bool DcCommandType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DcStatusCodes_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_depthCams_2eproto);
  return file_level_enum_descriptors_depthCams_2eproto[2];
}
bool DcStatusCodes_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Acknowledge::_Internal {
 public:
};

Acknowledge::Acknowledge(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DepthCameras.Acknowledge)
}
Acknowledge::Acknowledge(const Acknowledge& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Acknowledge* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.acknowledged_type_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.command_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_command_id().empty()) {
    _this->_impl_.command_id_.Set(from._internal_command_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.acknowledged_type_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.acknowledged_type_));
  // @@protoc_insertion_point(copy_constructor:DepthCameras.Acknowledge)
}

inline void Acknowledge::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.acknowledged_type_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.command_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Acknowledge::~Acknowledge() {
  // @@protoc_insertion_point(destructor:DepthCameras.Acknowledge)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Acknowledge::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.command_id_.Destroy();
}

void Acknowledge::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Acknowledge::Clear() {
// @@protoc_insertion_point(message_clear_start:DepthCameras.Acknowledge)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.command_id_.ClearToEmpty();
  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.acknowledged_type_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.acknowledged_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Acknowledge::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .DepthCameras.MessageType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::DepthCameras::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // string command_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_command_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DepthCameras.Acknowledge.command_id"));
        } else
          goto handle_unusual;
        continue;
      // .DepthCameras.MessageType acknowledged_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_acknowledged_type(static_cast<::DepthCameras::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Acknowledge::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DepthCameras.Acknowledge)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .DepthCameras.MessageType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // string command_id = 2;
  if (!this->_internal_command_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_command_id().data(), static_cast<int>(this->_internal_command_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DepthCameras.Acknowledge.command_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_command_id(), target);
  }

  // .DepthCameras.MessageType acknowledged_type = 3;
  if (this->_internal_acknowledged_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_acknowledged_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DepthCameras.Acknowledge)
  return target;
}

size_t Acknowledge::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DepthCameras.Acknowledge)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string command_id = 2;
  if (!this->_internal_command_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_command_id());
  }

  // .DepthCameras.MessageType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // .DepthCameras.MessageType acknowledged_type = 3;
  if (this->_internal_acknowledged_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_acknowledged_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Acknowledge::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Acknowledge::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Acknowledge::GetClassData() const { return &_class_data_; }


void Acknowledge::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Acknowledge*>(&to_msg);
  auto& from = static_cast<const Acknowledge&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DepthCameras.Acknowledge)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_command_id().empty()) {
    _this->_internal_set_command_id(from._internal_command_id());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_acknowledged_type() != 0) {
    _this->_internal_set_acknowledged_type(from._internal_acknowledged_type());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Acknowledge::CopyFrom(const Acknowledge& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DepthCameras.Acknowledge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Acknowledge::IsInitialized() const {
  return true;
}

void Acknowledge::InternalSwap(Acknowledge* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.command_id_, lhs_arena,
      &other->_impl_.command_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Acknowledge, _impl_.acknowledged_type_)
      + sizeof(Acknowledge::_impl_.acknowledged_type_)
      - PROTOBUF_FIELD_OFFSET(Acknowledge, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Acknowledge::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_depthCams_2eproto_getter, &descriptor_table_depthCams_2eproto_once,
      file_level_metadata_depthCams_2eproto[0]);
}

// ===================================================================

class CommandStatusUpdate::_Internal {
 public:
};

CommandStatusUpdate::CommandStatusUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DepthCameras.CommandStatusUpdate)
}
CommandStatusUpdate::CommandStatusUpdate(const CommandStatusUpdate& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CommandStatusUpdate* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){}
    , decltype(_impl_.msg_type_){}
    , decltype(_impl_.status_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.command_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_command_id().empty()) {
    _this->_impl_.command_id_.Set(from._internal_command_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.msg_type_, &from._impl_.msg_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.status_code_) -
    reinterpret_cast<char*>(&_impl_.msg_type_)) + sizeof(_impl_.status_code_));
  // @@protoc_insertion_point(copy_constructor:DepthCameras.CommandStatusUpdate)
}

inline void CommandStatusUpdate::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){}
    , decltype(_impl_.msg_type_){0}
    , decltype(_impl_.status_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.command_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CommandStatusUpdate::~CommandStatusUpdate() {
  // @@protoc_insertion_point(destructor:DepthCameras.CommandStatusUpdate)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CommandStatusUpdate::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.command_id_.Destroy();
}

void CommandStatusUpdate::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CommandStatusUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:DepthCameras.CommandStatusUpdate)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.command_id_.ClearToEmpty();
  ::memset(&_impl_.msg_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.status_code_) -
      reinterpret_cast<char*>(&_impl_.msg_type_)) + sizeof(_impl_.status_code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CommandStatusUpdate::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .DepthCameras.MessageType msg_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_msg_type(static_cast<::DepthCameras::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // string command_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_command_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DepthCameras.CommandStatusUpdate.command_id"));
        } else
          goto handle_unusual;
        continue;
      // int32 status_code = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.status_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CommandStatusUpdate::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DepthCameras.CommandStatusUpdate)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .DepthCameras.MessageType msg_type = 1;
  if (this->_internal_msg_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_msg_type(), target);
  }

  // string command_id = 2;
  if (!this->_internal_command_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_command_id().data(), static_cast<int>(this->_internal_command_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DepthCameras.CommandStatusUpdate.command_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_command_id(), target);
  }

  // int32 status_code = 3;
  if (this->_internal_status_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_status_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DepthCameras.CommandStatusUpdate)
  return target;
}

size_t CommandStatusUpdate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DepthCameras.CommandStatusUpdate)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string command_id = 2;
  if (!this->_internal_command_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_command_id());
  }

  // .DepthCameras.MessageType msg_type = 1;
  if (this->_internal_msg_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_msg_type());
  }

  // int32 status_code = 3;
  if (this->_internal_status_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_status_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CommandStatusUpdate::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CommandStatusUpdate::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CommandStatusUpdate::GetClassData() const { return &_class_data_; }


void CommandStatusUpdate::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CommandStatusUpdate*>(&to_msg);
  auto& from = static_cast<const CommandStatusUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DepthCameras.CommandStatusUpdate)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_command_id().empty()) {
    _this->_internal_set_command_id(from._internal_command_id());
  }
  if (from._internal_msg_type() != 0) {
    _this->_internal_set_msg_type(from._internal_msg_type());
  }
  if (from._internal_status_code() != 0) {
    _this->_internal_set_status_code(from._internal_status_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CommandStatusUpdate::CopyFrom(const CommandStatusUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DepthCameras.CommandStatusUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandStatusUpdate::IsInitialized() const {
  return true;
}

void CommandStatusUpdate::InternalSwap(CommandStatusUpdate* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.command_id_, lhs_arena,
      &other->_impl_.command_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CommandStatusUpdate, _impl_.status_code_)
      + sizeof(CommandStatusUpdate::_impl_.status_code_)
      - PROTOBUF_FIELD_OFFSET(CommandStatusUpdate, _impl_.msg_type_)>(
          reinterpret_cast<char*>(&_impl_.msg_type_),
          reinterpret_cast<char*>(&other->_impl_.msg_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CommandStatusUpdate::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_depthCams_2eproto_getter, &descriptor_table_depthCams_2eproto_once,
      file_level_metadata_depthCams_2eproto[1]);
}

// ===================================================================

class DcRequest::_Internal {
 public:
};

DcRequest::DcRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DepthCameras.DcRequest)
}
DcRequest::DcRequest(const DcRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DcRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){}
    , decltype(_impl_.message_data_){}
    , decltype(_impl_.dc_cmd_type_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.message_size_){}
    , decltype(_impl_.is_acknowledge_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.command_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_command_id().empty()) {
    _this->_impl_.command_id_.Set(from._internal_command_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_data().empty()) {
    _this->_impl_.message_data_.Set(from._internal_message_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.dc_cmd_type_, &from._impl_.dc_cmd_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_acknowledge_) -
    reinterpret_cast<char*>(&_impl_.dc_cmd_type_)) + sizeof(_impl_.is_acknowledge_));
  // @@protoc_insertion_point(copy_constructor:DepthCameras.DcRequest)
}

inline void DcRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){}
    , decltype(_impl_.message_data_){}
    , decltype(_impl_.dc_cmd_type_){0}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.message_size_){0}
    , decltype(_impl_.is_acknowledge_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.command_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DcRequest::~DcRequest() {
  // @@protoc_insertion_point(destructor:DepthCameras.DcRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DcRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.command_id_.Destroy();
  _impl_.message_data_.Destroy();
}

void DcRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DcRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:DepthCameras.DcRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.command_id_.ClearToEmpty();
  _impl_.message_data_.ClearToEmpty();
  ::memset(&_impl_.dc_cmd_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_acknowledge_) -
      reinterpret_cast<char*>(&_impl_.dc_cmd_type_)) + sizeof(_impl_.is_acknowledge_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DcRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string command_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_command_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DepthCameras.DcRequest.command_id"));
        } else
          goto handle_unusual;
        continue;
      // .DepthCameras.DcCommandType dc_cmd_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_dc_cmd_type(static_cast<::DepthCameras::DcCommandType>(val));
        } else
          goto handle_unusual;
        continue;
      // .DepthCameras.MessageType type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::DepthCameras::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 message_size = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.message_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes message_data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_message_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_acknowledge = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.is_acknowledge_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DcRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DepthCameras.DcRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string command_id = 1;
  if (!this->_internal_command_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_command_id().data(), static_cast<int>(this->_internal_command_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DepthCameras.DcRequest.command_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_command_id(), target);
  }

  // .DepthCameras.DcCommandType dc_cmd_type = 2;
  if (this->_internal_dc_cmd_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_dc_cmd_type(), target);
  }

  // .DepthCameras.MessageType type = 3;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_type(), target);
  }

  // int32 message_size = 4;
  if (this->_internal_message_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_message_size(), target);
  }

  // bytes message_data = 5;
  if (!this->_internal_message_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_message_data(), target);
  }

  // bool is_acknowledge = 6;
  if (this->_internal_is_acknowledge() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_is_acknowledge(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DepthCameras.DcRequest)
  return target;
}

size_t DcRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DepthCameras.DcRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string command_id = 1;
  if (!this->_internal_command_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_command_id());
  }

  // bytes message_data = 5;
  if (!this->_internal_message_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_message_data());
  }

  // .DepthCameras.DcCommandType dc_cmd_type = 2;
  if (this->_internal_dc_cmd_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_dc_cmd_type());
  }

  // .DepthCameras.MessageType type = 3;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // int32 message_size = 4;
  if (this->_internal_message_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_message_size());
  }

  // bool is_acknowledge = 6;
  if (this->_internal_is_acknowledge() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DcRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DcRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DcRequest::GetClassData() const { return &_class_data_; }


void DcRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DcRequest*>(&to_msg);
  auto& from = static_cast<const DcRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DepthCameras.DcRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_command_id().empty()) {
    _this->_internal_set_command_id(from._internal_command_id());
  }
  if (!from._internal_message_data().empty()) {
    _this->_internal_set_message_data(from._internal_message_data());
  }
  if (from._internal_dc_cmd_type() != 0) {
    _this->_internal_set_dc_cmd_type(from._internal_dc_cmd_type());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_message_size() != 0) {
    _this->_internal_set_message_size(from._internal_message_size());
  }
  if (from._internal_is_acknowledge() != 0) {
    _this->_internal_set_is_acknowledge(from._internal_is_acknowledge());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DcRequest::CopyFrom(const DcRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DepthCameras.DcRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DcRequest::IsInitialized() const {
  return true;
}

void DcRequest::InternalSwap(DcRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.command_id_, lhs_arena,
      &other->_impl_.command_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_data_, lhs_arena,
      &other->_impl_.message_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DcRequest, _impl_.is_acknowledge_)
      + sizeof(DcRequest::_impl_.is_acknowledge_)
      - PROTOBUF_FIELD_OFFSET(DcRequest, _impl_.dc_cmd_type_)>(
          reinterpret_cast<char*>(&_impl_.dc_cmd_type_),
          reinterpret_cast<char*>(&other->_impl_.dc_cmd_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DcRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_depthCams_2eproto_getter, &descriptor_table_depthCams_2eproto_once,
      file_level_metadata_depthCams_2eproto[2]);
}

// ===================================================================

class DcResponse::_Internal {
 public:
};

DcResponse::DcResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DepthCameras.DcResponse)
}
DcResponse::DcResponse(const DcResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DcResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){}
    , decltype(_impl_.message_data_){}
    , decltype(_impl_.dc_cmd_type_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.message_size_){}
    , decltype(_impl_.is_acknowledge_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.command_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_command_id().empty()) {
    _this->_impl_.command_id_.Set(from._internal_command_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_data().empty()) {
    _this->_impl_.message_data_.Set(from._internal_message_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.dc_cmd_type_, &from._impl_.dc_cmd_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_acknowledge_) -
    reinterpret_cast<char*>(&_impl_.dc_cmd_type_)) + sizeof(_impl_.is_acknowledge_));
  // @@protoc_insertion_point(copy_constructor:DepthCameras.DcResponse)
}

inline void DcResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.command_id_){}
    , decltype(_impl_.message_data_){}
    , decltype(_impl_.dc_cmd_type_){0}
    , decltype(_impl_.type_){0}
    , decltype(_impl_.message_size_){0}
    , decltype(_impl_.is_acknowledge_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.command_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.command_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DcResponse::~DcResponse() {
  // @@protoc_insertion_point(destructor:DepthCameras.DcResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DcResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.command_id_.Destroy();
  _impl_.message_data_.Destroy();
}

void DcResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DcResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:DepthCameras.DcResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.command_id_.ClearToEmpty();
  _impl_.message_data_.ClearToEmpty();
  ::memset(&_impl_.dc_cmd_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_acknowledge_) -
      reinterpret_cast<char*>(&_impl_.dc_cmd_type_)) + sizeof(_impl_.is_acknowledge_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DcResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string command_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_command_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DepthCameras.DcResponse.command_id"));
        } else
          goto handle_unusual;
        continue;
      // .DepthCameras.DcCommandType dc_cmd_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_dc_cmd_type(static_cast<::DepthCameras::DcCommandType>(val));
        } else
          goto handle_unusual;
        continue;
      // .DepthCameras.MessageType type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::DepthCameras::MessageType>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 message_size = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.message_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes message_data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_message_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_acknowledge = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.is_acknowledge_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DcResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DepthCameras.DcResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string command_id = 1;
  if (!this->_internal_command_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_command_id().data(), static_cast<int>(this->_internal_command_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DepthCameras.DcResponse.command_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_command_id(), target);
  }

  // .DepthCameras.DcCommandType dc_cmd_type = 2;
  if (this->_internal_dc_cmd_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_dc_cmd_type(), target);
  }

  // .DepthCameras.MessageType type = 3;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_type(), target);
  }

  // int32 message_size = 4;
  if (this->_internal_message_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_message_size(), target);
  }

  // bytes message_data = 5;
  if (!this->_internal_message_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_message_data(), target);
  }

  // bool is_acknowledge = 6;
  if (this->_internal_is_acknowledge() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_is_acknowledge(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DepthCameras.DcResponse)
  return target;
}

size_t DcResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DepthCameras.DcResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string command_id = 1;
  if (!this->_internal_command_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_command_id());
  }

  // bytes message_data = 5;
  if (!this->_internal_message_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_message_data());
  }

  // .DepthCameras.DcCommandType dc_cmd_type = 2;
  if (this->_internal_dc_cmd_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_dc_cmd_type());
  }

  // .DepthCameras.MessageType type = 3;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // int32 message_size = 4;
  if (this->_internal_message_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_message_size());
  }

  // bool is_acknowledge = 6;
  if (this->_internal_is_acknowledge() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DcResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DcResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DcResponse::GetClassData() const { return &_class_data_; }


void DcResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DcResponse*>(&to_msg);
  auto& from = static_cast<const DcResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DepthCameras.DcResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_command_id().empty()) {
    _this->_internal_set_command_id(from._internal_command_id());
  }
  if (!from._internal_message_data().empty()) {
    _this->_internal_set_message_data(from._internal_message_data());
  }
  if (from._internal_dc_cmd_type() != 0) {
    _this->_internal_set_dc_cmd_type(from._internal_dc_cmd_type());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_message_size() != 0) {
    _this->_internal_set_message_size(from._internal_message_size());
  }
  if (from._internal_is_acknowledge() != 0) {
    _this->_internal_set_is_acknowledge(from._internal_is_acknowledge());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DcResponse::CopyFrom(const DcResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DepthCameras.DcResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DcResponse::IsInitialized() const {
  return true;
}

void DcResponse::InternalSwap(DcResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.command_id_, lhs_arena,
      &other->_impl_.command_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_data_, lhs_arena,
      &other->_impl_.message_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DcResponse, _impl_.is_acknowledge_)
      + sizeof(DcResponse::_impl_.is_acknowledge_)
      - PROTOBUF_FIELD_OFFSET(DcResponse, _impl_.dc_cmd_type_)>(
          reinterpret_cast<char*>(&_impl_.dc_cmd_type_),
          reinterpret_cast<char*>(&other->_impl_.dc_cmd_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DcResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_depthCams_2eproto_getter, &descriptor_table_depthCams_2eproto_once,
      file_level_metadata_depthCams_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace DepthCameras
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::DepthCameras::Acknowledge*
Arena::CreateMaybeMessage< ::DepthCameras::Acknowledge >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DepthCameras::Acknowledge >(arena);
}
template<> PROTOBUF_NOINLINE ::DepthCameras::CommandStatusUpdate*
Arena::CreateMaybeMessage< ::DepthCameras::CommandStatusUpdate >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DepthCameras::CommandStatusUpdate >(arena);
}
template<> PROTOBUF_NOINLINE ::DepthCameras::DcRequest*
Arena::CreateMaybeMessage< ::DepthCameras::DcRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DepthCameras::DcRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::DepthCameras::DcResponse*
Arena::CreateMaybeMessage< ::DepthCameras::DcResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DepthCameras::DcResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
