//
// Created by nkaffine on 12/2/19.
// Copyright (c) 2019 Fulfil Solutions, Inc. All rights reserved.
//
/**
 * This file contains the implementation of the presets for
 * the realsense sensors. It is essentially copy and pasted
 * json files to not rely on relative filepaths in the code.
 */
#include "device_presets.h"
#include <string>
#include <memory>

using fulfil::depthcam::DevicePresets;


//TODO this is a string known at compile time. This should 100% be on the stack as a constexpr string literal
// Oh geez, and it is defined as static. Clean and test when we get the chance
std::shared_ptr<std::string> DevicePresets::D455_adjusted()
{
    std::shared_ptr<std::string> preset_json = std::make_shared<std::string>("{\n"
                        "    \"aux-param-autoexposure-setpoint\":\"400\",\n"
                        "    \"aux-param-colorcorrection1\":\"-0.493164\",\n"
                        "    \"aux-param-colorcorrection10\":\"-0.272461\",\n"
                        "    \"aux-param-colorcorrection11\":\"-0.272461\",\n"
                        "    \"aux-param-colorcorrection12\":\"-0.355469\",\n"
                        "    \"aux-param-colorcorrection2\":\"0.831055\",\n"
                        "    \"aux-param-colorcorrection3\":\"0.831055\",\n"
                        "    \"aux-param-colorcorrection4\":\"-0.368164\",\n"
                        "    \"aux-param-colorcorrection5\":\"-0.133789\",\n"
                        "    \"aux-param-colorcorrection6\":\"-0.323242\",\n"
                        "    \"aux-param-colorcorrection7\":\"-0.323242\",\n"
                        "    \"aux-param-colorcorrection8\":\"1.19141\",\n"
                        "    \"aux-param-colorcorrection9\":\"0.90918\",\n"
                        "    \"aux-param-depthclampmax\":\"65536\",\n"
                        "    \"aux-param-depthclampmin\":\"0\",\n"
                        "    \"aux-param-disparityshift\":\"20\",\n"
                        "    \"controls-autoexposure-auto\":\"True\",\n"
                        "    \"controls-autoexposure-manual\":\"33000\",\n"
                        "    \"controls-color-autoexposure-auto\":\"True\",\n"
                        "    \"controls-color-autoexposure-manual\":\"156\",\n"
                        "    \"controls-color-backlight-compensation\":\"0\",\n"
                        "    \"controls-color-brightness\":\"0\",\n"
                        "    \"controls-color-contrast\":\"50\",\n"
                        "    \"controls-color-gain\":\"64\",\n"
                        "    \"controls-color-gamma\":\"300\",\n"
                        "    \"controls-color-hue\":\"0\",\n"
                        "    \"controls-color-power-line-frequency\":\"3\",\n"
                        "    \"controls-color-saturation\":\"64\",\n"
                        "    \"controls-color-sharpness\":\"50\",\n"
                        "    \"controls-color-white-balance-auto\":\"True\",\n"
                        "    \"controls-color-white-balance-manual\":\"4600\",\n"
                        "    \"controls-depth-gain\":\"16\",\n"
                        "    \"controls-laserpower\":\"150\",\n"
                        "    \"controls-laserstate\":\"on\",\n"
                        "    \"ignoreSAD\":\"0\",\n"
                        "    \"param-amplitude-factor\":\"0.08\",\n"
                        "    \"param-autoexposure-setpoint\":\"400\",\n"
                        "    \"param-censusenablereg-udiameter\":\"9\",\n"
                        "    \"param-censusenablereg-vdiameter\":\"9\",\n"
                        "    \"param-censususize\":\"9\",\n"
                        "    \"param-censusvsize\":\"9\",\n"
                        "    \"param-depthclampmax\":\"65536\",\n"
                        "    \"param-depthclampmin\":\"0\",\n"
                        "    \"param-depthunits\":\"1000\",\n"
                        "    \"param-disableraucolor\":\"0\",\n"
                        "    \"param-disablesadcolor\":\"0\",\n"
                        "    \"param-disablesadnormalize\":\"0\",\n"
                        "    \"param-disablesloleftcolor\":\"0\",\n"
                        "    \"param-disableslorightcolor\":\"0\",\n"
                        "    \"param-disparitymode\":\"0\",\n"
                        "    \"param-disparityshift\":\"20\",\n"
                        "    \"param-lambdaad\":\"800\",\n"
                        "    \"param-lambdacensus\":\"26\",\n"
                        "    \"param-leftrightthreshold\":\"24\",\n"
                        "    \"param-maxscorethreshb\":\"700\",\n"
                        "    \"param-medianthreshold\":\"500\",\n"
                        "    \"param-minscorethresha\":\"1\",\n"
                        "    \"param-neighborthresh\":\"7\",\n"
                        "    \"param-raumine\":\"1\",\n"
                        "    \"param-rauminn\":\"1\",\n"
                        "    \"param-rauminnssum\":\"3\",\n"
                        "    \"param-raumins\":\"1\",\n"
                        "    \"param-rauminw\":\"1\",\n"
                        "    \"param-rauminwesum\":\"3\",\n"
                        "    \"param-regioncolorthresholdb\":\"0.0499022\",\n"
                        "    \"param-regioncolorthresholdg\":\"0.0499022\",\n"
                        "    \"param-regioncolorthresholdr\":\"0.0499022\",\n"
                        "    \"param-regionshrinku\":\"3\",\n"
                        "    \"param-regionshrinkv\":\"1\",\n"
                        "    \"param-robbinsmonrodecrement\":\"10\",\n"
                        "    \"param-robbinsmonroincrement\":\"10\",\n"
                        "    \"param-rsmdiffthreshold\":\"4\",\n"
                        "    \"param-rsmrauslodiffthreshold\":\"1\",\n"
                        "    \"param-rsmremovethreshold\":\"0.375\",\n"
                        "    \"param-scanlineedgetaub\":\"72\",\n"
                        "    \"param-scanlineedgetaug\":\"72\",\n"
                        "    \"param-scanlineedgetaur\":\"72\",\n"
                        "    \"param-scanlinep1\":\"60\",\n"
                        "    \"param-scanlinep1onediscon\":\"105\",\n"
                        "    \"param-scanlinep1twodiscon\":\"70\",\n"
                        "    \"param-scanlinep2\":\"342\",\n"
                        "    \"param-scanlinep2onediscon\":\"190\",\n"
                        "    \"param-scanlinep2twodiscon\":\"130\",\n"
                        "    \"param-secondpeakdelta\":\"325\",\n"
                        "    \"param-texturecountthresh\":\"0\",\n"
                        "    \"param-texturedifferencethresh\":\"0\",\n"
                        "    \"param-usersm\":\"1\",\n"
                        "    \"param-zunits\":\"1000\",\n"
                        "    \"stream-depth-format\":\"Z16\",\n"
                        "    \"stream-fps\":\"30\",\n"
                        "    \"stream-height\":\"480\",\n"
                        "    \"stream-width\":\"848\"\n"
                        "}");
    return preset_json;
}

std::shared_ptr<std::string> DevicePresets::D455_default()
{
    std::shared_ptr<std::string> preset_json = std::make_shared<std::string>("{\n"
                        "    \"aux-param-autoexposure-setpoint\": \"1000\",\n"
                        "    \"aux-param-colorcorrection1\": \"-0.493164\",\n"
                        "    \"aux-param-colorcorrection10\": \"-0.272461\",\n"
                        "    \"aux-param-colorcorrection11\": \"-0.272461\",\n"
                        "    \"aux-param-colorcorrection12\": \"-0.355469\",\n"
                        "    \"aux-param-colorcorrection2\": \"0.831055\",\n"
                        "    \"aux-param-colorcorrection3\": \"0.831055\",\n"
                        "    \"aux-param-colorcorrection4\": \"-0.368164\",\n"
                        "    \"aux-param-colorcorrection5\": \"-0.133789\",\n"
                        "    \"aux-param-colorcorrection6\": \"-0.323242\",\n"
                        "    \"aux-param-colorcorrection7\": \"-0.323242\",\n"
                        "    \"aux-param-colorcorrection8\": \"1.19141\",\n"
                        "    \"aux-param-colorcorrection9\": \"0.90918\",\n"
                        "    \"aux-param-depthclampmax\": \"65536\",\n"
                        "    \"aux-param-depthclampmin\": \"0\",\n"
                        "    \"aux-param-disparityshift\": \"0\",\n"
                        "    \"controls-autoexposure-auto\": \"True\",\n"
                        "    \"controls-autoexposure-manual\": \"32000\",\n"
                        "    \"controls-color-autoexposure-auto\": \"True\",\n"
                        "    \"controls-color-autoexposure-manual\": \"156\",\n"
                        "    \"controls-color-backlight-compensation\": \"0\",\n"
                        "    \"controls-color-brightness\": \"0\",\n"
                        "    \"controls-color-contrast\": \"50\",\n"
                        "    \"controls-color-gain\": \"64\",\n"
                        "    \"controls-color-gamma\": \"300\",\n"
                        "    \"controls-color-hue\": \"0\",\n"
                        "    \"controls-color-power-line-frequency\": \"3\",\n"
                        "    \"controls-color-saturation\": \"64\",\n"
                        "    \"controls-color-sharpness\": \"50\",\n"
                        "    \"controls-color-white-balance-auto\": \"True\",\n"
                        "    \"controls-color-white-balance-manual\": \"4600\",\n"
                        "    \"controls-depth-gain\": \"16\",\n"
                        "    \"controls-laserpower\": \"150\",\n"
                        "    \"controls-laserstate\": \"on\",\n"
                        "    \"ignoreSAD\": \"0\",\n"
                        "    \"param-amplitude-factor\": \"0\",\n"
                        "    \"param-autoexposure-setpoint\": \"1000\",\n"
                        "    \"param-censusenablereg-udiameter\": \"9\",\n"
                        "    \"param-censusenablereg-vdiameter\": \"9\",\n"
                        "    \"param-censususize\": \"9\",\n"
                        "    \"param-censusvsize\": \"9\",\n"
                        "    \"param-depthclampmax\": \"65536\",\n"
                        "    \"param-depthclampmin\": \"0\",\n"
                        "    \"param-depthunits\": \"1000\",\n"
                        "    \"param-disableraucolor\": \"0\",\n"
                        "    \"param-disablesadcolor\": \"0\",\n"
                        "    \"param-disablesadnormalize\": \"0\",\n"
                        "    \"param-disablesloleftcolor\": \"0\",\n"
                        "    \"param-disableslorightcolor\": \"0\",\n"
                        "    \"param-disparitymode\": \"0\",\n"
                        "    \"param-disparityshift\": \"0\",\n"
                        "    \"param-lambdaad\": \"800\",\n"
                        "    \"param-lambdacensus\": \"26\",\n"
                        "    \"param-leftrightthreshold\": \"24\",\n"
                        "    \"param-maxscorethreshb\": \"2047\",\n"
                        "    \"param-medianthreshold\": \"500\",\n"
                        "    \"param-minscorethresha\": \"1\",\n"
                        "    \"param-neighborthresh\": \"7\",\n"
                        "    \"param-raumine\": \"1\",\n"
                        "    \"param-rauminn\": \"1\",\n"
                        "    \"param-rauminnssum\": \"3\",\n"
                        "    \"param-raumins\": \"1\",\n"
                        "    \"param-rauminw\": \"1\",\n"
                        "    \"param-rauminwesum\": \"3\",\n"
                        "    \"param-regioncolorthresholdb\": \"0.0499022\",\n"
                        "    \"param-regioncolorthresholdg\": \"0.0499022\",\n"
                        "    \"param-regioncolorthresholdr\": \"0.0499022\",\n"
                        "    \"param-regionshrinku\": \"3\",\n"
                        "    \"param-regionshrinkv\": \"1\",\n"
                        "    \"param-robbinsmonrodecrement\": \"10\",\n"
                        "    \"param-robbinsmonroincrement\": \"10\",\n"
                        "    \"param-rsmdiffthreshold\": \"4\",\n"
                        "    \"param-rsmrauslodiffthreshold\": \"1\",\n"
                        "    \"param-rsmremovethreshold\": \"0.375\",\n"
                        "    \"param-scanlineedgetaub\": \"72\",\n"
                        "    \"param-scanlineedgetaug\": \"72\",\n"
                        "    \"param-scanlineedgetaur\": \"72\",\n"
                        "    \"param-scanlinep1\": \"60\",\n"
                        "    \"param-scanlinep1onediscon\": \"105\",\n"
                        "    \"param-scanlinep1twodiscon\": \"70\",\n"
                        "    \"param-scanlinep2\": \"342\",\n"
                        "    \"param-scanlinep2onediscon\": \"190\",\n"
                        "    \"param-scanlinep2twodiscon\": \"130\",\n"
                        "    \"param-secondpeakdelta\": \"325\",\n"
                        "    \"param-texturecountthresh\": \"0\",\n"
                        "    \"param-texturedifferencethresh\": \"0\",\n"
                        "    \"param-usersm\": \"1\",\n"
                        "    \"param-zunits\": \"1000\",\n"
                        "    \"stream-depth-format\": \"Z16\",\n"
                        "    \"stream-fps\": \"30\",\n"
                        "    \"stream-height\": \"720\",\n"
                        "    \"stream-width\": \"1280\"\n"
                            "}");
    return preset_json;
}

std::shared_ptr<std::string> DevicePresets::D415_high_accuracy()
{
    std::shared_ptr<std::string> preset_json = std::make_shared<std::string>("{\n"
                        "    \"aux-param-autoexposure-setpoint\": \"400\",\n"
                        "    \"aux-param-colorcorrection1\": \"0.461914\",\n"
                        "    \"aux-param-colorcorrection10\": \"-0.553711\",\n"
                        "    \"aux-param-colorcorrection11\": \"-0.553711\",\n"
                        "    \"aux-param-colorcorrection12\": \"0.0458984\",\n"
                        "    \"aux-param-colorcorrection2\": \"0.540039\",\n"
                        "    \"aux-param-colorcorrection3\": \"0.540039\",\n"
                        "    \"aux-param-colorcorrection4\": \"0.208008\",\n"
                        "    \"aux-param-colorcorrection5\": \"-0.332031\",\n"
                        "    \"aux-param-colorcorrection6\": \"-0.212891\",\n"
                        "    \"aux-param-colorcorrection7\": \"-0.212891\",\n"
                        "    \"aux-param-colorcorrection8\": \"0.68457\",\n"
                        "    \"aux-param-colorcorrection9\": \"0.930664\",\n"
                        "    \"aux-param-depthclampmax\": \"65536\",\n"
                        "    \"aux-param-depthclampmin\": \"0\",\n"
                        "    \"aux-param-disparityshift\": \"0\",\n"
                        "    \"controls-autoexposure-auto\": \"True\",\n"
                        "    \"controls-autoexposure-manual\": \"32000\",\n"
                        "    \"controls-color-autoexposure-auto\": \"True\",\n"
                        "    \"controls-color-autoexposure-manual\": \"156\",\n"
                        "    \"controls-color-backlight-compensation\": \"0\",\n"
                        "    \"controls-color-brightness\": \"0\",\n"
                        "    \"controls-color-contrast\": \"50\",\n"
                        "    \"controls-color-gain\": \"64\",\n"
                        "    \"controls-color-gamma\": \"300\",\n"
                        "    \"controls-color-hue\": \"0\",\n"
                        "    \"controls-color-power-line-frequency\": \"3\",\n"
                        "    \"controls-color-saturation\": \"64\",\n"
                        "    \"controls-color-sharpness\": \"50\",\n"
                        "    \"controls-color-white-balance-auto\": \"False\",\n"
                        "    \"controls-color-white-balance-manual\": \"7000\",\n"
                        "    \"controls-depth-gain\": \"16\",\n"
                        "    \"controls-depth-white-balance-auto\": \"False\",\n"
                        "    \"controls-laserpower\": \"150\",\n"
                        "    \"controls-laserstate\": \"on\",\n"
                        "    \"ignoreSAD\": \"0\",\n"
                        "    \"param-amplitude-factor\": \"0\",\n"
                        "    \"param-autoexposure-setpoint\": \"400\",\n"
                        "    \"param-censusenablereg-udiameter\": \"9\",\n"
                        "    \"param-censusenablereg-vdiameter\": \"9\",\n"
                        "    \"param-censususize\": \"9\",\n"
                        "    \"param-censusvsize\": \"9\",\n"
                        "    \"param-depthclampmax\": \"65536\",\n"
                        "    \"param-depthclampmin\": \"0\",\n"
                        "    \"param-depthunits\": \"1000\",\n"
                        "    \"param-disableraucolor\": \"0\",\n"
                        "    \"param-disablesadcolor\": \"0\",\n"
                        "    \"param-disablesadnormalize\": \"0\",\n"
                        "    \"param-disablesloleftcolor\": \"0\",\n"
                        "    \"param-disableslorightcolor\": \"1\",\n"
                        "    \"param-disparitymode\": \"0\",\n"
                        "    \"param-disparityshift\": \"0\",\n"
                        "    \"param-lambdaad\": \"751\",\n"
                        "    \"param-lambdacensus\": \"6\",\n"
                        "    \"param-leftrightthreshold\": \"10\",\n"
                        "    \"param-maxscorethreshb\": \"2893\",\n"
                        "    \"param-medianthreshold\": \"796\",\n"
                        "    \"param-minscorethresha\": \"4\",\n"
                        "    \"param-neighborthresh\": \"108\",\n"
                        "    \"param-raumine\": \"6\",\n"
                        "    \"param-rauminn\": \"3\",\n"
                        "    \"param-rauminnssum\": \"7\",\n"
                        "    \"param-raumins\": \"2\",\n"
                        "    \"param-rauminw\": \"2\",\n"
                        "    \"param-rauminwesum\": \"12\",\n"
                        "    \"param-regioncolorthresholdb\": \"0.785714\",\n"
                        "    \"param-regioncolorthresholdg\": \"0.565558\",\n"
                        "    \"param-regioncolorthresholdr\": \"0.985323\",\n"
                        "    \"param-regionshrinku\": \"3\",\n"
                        "    \"param-regionshrinkv\": \"0\",\n"
                        "    \"param-robbinsmonrodecrement\": \"25\",\n"
                        "    \"param-robbinsmonroincrement\": \"2\",\n"
                        "    \"param-rsmdiffthreshold\": \"1.65625\",\n"
                        "    \"param-rsmrauslodiffthreshold\": \"0.71875\",\n"
                        "    \"param-rsmremovethreshold\": \"0.809524\",\n"
                        "    \"param-scanlineedgetaub\": \"13\",\n"
                        "    \"param-scanlineedgetaug\": \"15\",\n"
                        "    \"param-scanlineedgetaur\": \"30\",\n"
                        "    \"param-scanlinep1\": \"155\",\n"
                        "    \"param-scanlinep1onediscon\": \"160\",\n"
                        "    \"param-scanlinep1twodiscon\": \"59\",\n"
                        "    \"param-scanlinep2\": \"190\",\n"
                        "    \"param-scanlinep2onediscon\": \"507\",\n"
                        "    \"param-scanlinep2twodiscon\": \"493\",\n"
                        "    \"param-secondpeakdelta\": \"647\",\n"
                        "    \"param-texturecountthresh\": \"0\",\n"
                        "    \"param-texturedifferencethresh\": \"1722\",\n"
                        "    \"param-usersm\": \"1\",\n"
                        "    \"param-zunits\": \"1000\",\n"
                        "    \"stream-depth-format\": \"Z16\",\n"
                        "    \"stream-fps\": \"30\",\n"
                        "    \"stream-height\": \"720\",\n"
                        "    \"stream-width\": \"1280\"\n"
                            "}");
    return preset_json;
}

std::shared_ptr<std::string> DevicePresets::D415_frozen()
{
    std::shared_ptr<std::string> preset_json = std::make_shared<std::string>();
    preset_json->append("{\n"
                        "    \"aux-param-autoexposure-setpoint\": \"400\",\n"
                        "    \"aux-param-colorcorrection1\": \"0.461914\",\n"
                        "    \"aux-param-colorcorrection10\": \"-0.553711\",\n"
                        "    \"aux-param-colorcorrection11\": \"-0.553711\",\n"
                        "    \"aux-param-colorcorrection12\": \"0.0458984\",\n"
                        "    \"aux-param-colorcorrection2\": \"0.540039\",\n"
                        "    \"aux-param-colorcorrection3\": \"0.540039\",\n"
                        "    \"aux-param-colorcorrection4\": \"0.208008\",\n"
                        "    \"aux-param-colorcorrection5\": \"-0.332031\",\n"
                        "    \"aux-param-colorcorrection6\": \"-0.212891\",\n"
                        "    \"aux-param-colorcorrection7\": \"-0.212891\",\n"
                        "    \"aux-param-colorcorrection8\": \"0.68457\",\n"
                        "    \"aux-param-colorcorrection9\": \"0.930664\",\n"
                        "    \"aux-param-depthclampmax\": \"65536\",\n"
                        "    \"aux-param-depthclampmin\": \"0\",\n"
                        "    \"aux-param-disparityshift\": \"0\",\n"
                        "    \"controls-autoexposure-auto\": \"True\",\n"
                        "    \"controls-autoexposure-manual\": \"32000\",\n"
                        "    \"controls-color-autoexposure-auto\": \"True\",\n"
                        "    \"controls-color-autoexposure-manual\": \"156\",\n"
                        "    \"controls-color-backlight-compensation\": \"0\",\n"
                        "    \"controls-color-brightness\": \"0\",\n"
                        "    \"controls-color-contrast\": \"50\",\n"
                        "    \"controls-color-gain\": \"64\",\n"
                        "    \"controls-color-gamma\": \"300\",\n"
                        "    \"controls-color-hue\": \"0\",\n"
                        "    \"controls-color-power-line-frequency\": \"3\",\n"
                        "    \"controls-color-saturation\": \"64\",\n"
                        "    \"controls-color-sharpness\": \"50\",\n"
                        "    \"controls-color-white-balance-auto\": \"False\",\n"
                        "    \"controls-color-white-balance-manual\": \"7000\",\n"
                        "    \"controls-depth-gain\": \"16\",\n"
                        "    \"controls-depth-white-balance-auto\": \"False\",\n"
                        "    \"controls-laserpower\": \"0\",\n"
                        "    \"controls-laserstate\": \"off\",\n"
                        "    \"ignoreSAD\": \"0\",\n"
                        "    \"param-amplitude-factor\": \"0\",\n"
                        "    \"param-autoexposure-setpoint\": \"400\",\n"
                        "    \"param-censusenablereg-udiameter\": \"9\",\n"
                        "    \"param-censusenablereg-vdiameter\": \"9\",\n"
                        "    \"param-censususize\": \"9\",\n"
                        "    \"param-censusvsize\": \"9\",\n"
                        "    \"param-depthclampmax\": \"65536\",\n"
                        "    \"param-depthclampmin\": \"0\",\n"
                        "    \"param-depthunits\": \"1000\",\n"
                        "    \"param-disableraucolor\": \"0\",\n"
                        "    \"param-disablesadcolor\": \"0\",\n"
                        "    \"param-disablesadnormalize\": \"0\",\n"
                        "    \"param-disablesloleftcolor\": \"0\",\n"
                        "    \"param-disableslorightcolor\": \"1\",\n"
                        "    \"param-disparitymode\": \"0\",\n"
                        "    \"param-disparityshift\": \"0\",\n"
                        "    \"param-lambdaad\": \"751\",\n"
                        "    \"param-lambdacensus\": \"6\",\n"
                        "    \"param-leftrightthreshold\": \"10\",\n"
                        "    \"param-maxscorethreshb\": \"2893\",\n"
                        "    \"param-medianthreshold\": \"796\",\n"
                        "    \"param-minscorethresha\": \"4\",\n"
                        "    \"param-neighborthresh\": \"108\",\n"
                        "    \"param-raumine\": \"6\",\n"
                        "    \"param-rauminn\": \"3\",\n"
                        "    \"param-rauminnssum\": \"7\",\n"
                        "    \"param-raumins\": \"2\",\n"
                        "    \"param-rauminw\": \"2\",\n"
                        "    \"param-rauminwesum\": \"12\",\n"
                        "    \"param-regioncolorthresholdb\": \"0.785714\",\n"
                        "    \"param-regioncolorthresholdg\": \"0.565558\",\n"
                        "    \"param-regioncolorthresholdr\": \"0.985323\",\n"
                        "    \"param-regionshrinku\": \"3\",\n"
                        "    \"param-regionshrinkv\": \"0\",\n"
                        "    \"param-robbinsmonrodecrement\": \"25\",\n"
                        "    \"param-robbinsmonroincrement\": \"2\",\n"
                        "    \"param-rsmdiffthreshold\": \"1.65625\",\n"
                        "    \"param-rsmrauslodiffthreshold\": \"0.71875\",\n"
                        "    \"param-rsmremovethreshold\": \"0.809524\",\n"
                        "    \"param-scanlineedgetaub\": \"13\",\n"
                        "    \"param-scanlineedgetaug\": \"15\",\n"
                        "    \"param-scanlineedgetaur\": \"30\",\n"
                        "    \"param-scanlinep1\": \"155\",\n"
                        "    \"param-scanlinep1onediscon\": \"160\",\n"
                        "    \"param-scanlinep1twodiscon\": \"59\",\n"
                        "    \"param-scanlinep2\": \"190\",\n"
                        "    \"param-scanlinep2onediscon\": \"507\",\n"
                        "    \"param-scanlinep2twodiscon\": \"493\",\n"
                        "    \"param-secondpeakdelta\": \"647\",\n"
                        "    \"param-texturecountthresh\": \"0\",\n"
                        "    \"param-texturedifferencethresh\": \"1722\",\n"
                        "    \"param-usersm\": \"1\",\n"
                        "    \"param-zunits\": \"1000\",\n"
                        "    \"stream-depth-format\": \"Z16\",\n"
                        "    \"stream-fps\": \"30\",\n"
                        "    \"stream-height\": \"720\",\n"
                        "    \"stream-width\": \"1280\"\n"
                        "}");
    return preset_json;
}

std::shared_ptr<std::string> DevicePresets::D415_default()
{
    std::shared_ptr<std::string> preset_json = std::make_shared<std::string>("{\n"
                        "    \"aux-param-autoexposure-setpoint\": \"400\",\n"
                        "    \"aux-param-colorcorrection1\": \"0.461914\",\n"
                        "    \"aux-param-colorcorrection10\": \"-0.553711\",\n"
                        "    \"aux-param-colorcorrection11\": \"-0.553711\",\n"
                        "    \"aux-param-colorcorrection12\": \"0.0458984\",\n"
                        "    \"aux-param-colorcorrection2\": \"0.540039\",\n"
                        "    \"aux-param-colorcorrection3\": \"0.540039\",\n"
                        "    \"aux-param-colorcorrection4\": \"0.208008\",\n"
                        "    \"aux-param-colorcorrection5\": \"-0.332031\",\n"
                        "    \"aux-param-colorcorrection6\": \"-0.212891\",\n"
                        "    \"aux-param-colorcorrection7\": \"-0.212891\",\n"
                        "    \"aux-param-colorcorrection8\": \"0.68457\",\n"
                        "    \"aux-param-colorcorrection9\": \"0.930664\",\n"
                        "    \"aux-param-depthclampmax\": \"65536\",\n"
                        "    \"aux-param-depthclampmin\": \"0\",\n"
                        "    \"aux-param-disparityshift\": \"0\",\n"
                        "    \"controls-autoexposure-auto\": \"True\",\n"
                        "    \"controls-autoexposure-manual\": \"32000\",\n"
                        "    \"controls-color-autoexposure-auto\": \"True\",\n"
                        "    \"controls-color-autoexposure-manual\": \"156\",\n"
                        "    \"controls-color-backlight-compensation\": \"0\",\n"
                        "    \"controls-color-brightness\": \"0\",\n"
                        "    \"controls-color-contrast\": \"50\",\n"
                        "    \"controls-color-gain\": \"64\",\n"
                        "    \"controls-color-gamma\": \"300\",\n"
                        "    \"controls-color-hue\": \"0\",\n"
                        "    \"controls-color-power-line-frequency\": \"3\",\n"
                        "    \"controls-color-saturation\": \"64\",\n"
                        "    \"controls-color-sharpness\": \"50\",\n"
                        "    \"controls-color-white-balance-auto\": \"True\",\n"
                        "    \"controls-color-white-balance-manual\": \"4600\",\n"
                        "    \"controls-depth-gain\": \"16\",\n"
                        "    \"controls-depth-white-balance-auto\": \"False\",\n"
                        "    \"controls-laserpower\": \"150\",\n"
                        "    \"controls-laserstate\": \"on\",\n"
                        "    \"ignoreSAD\": \"0\",\n"
                        "    \"param-amplitude-factor\": \"0\",\n"
                        "    \"param-autoexposure-setpoint\": \"400\",\n"
                        "    \"param-censusenablereg-udiameter\": \"9\",\n"
                        "    \"param-censusenablereg-vdiameter\": \"9\",\n"
                        "    \"param-censususize\": \"9\",\n"
                        "    \"param-censusvsize\": \"9\",\n"
                        "    \"param-depthclampmax\": \"65536\",\n"
                        "    \"param-depthclampmin\": \"0\",\n"
                        "    \"param-depthunits\": \"1000\",\n"
                        "    \"param-disableraucolor\": \"0\",\n"
                        "    \"param-disablesadcolor\": \"0\",\n"
                        "    \"param-disablesadnormalize\": \"0\",\n"
                        "    \"param-disablesloleftcolor\": \"0\",\n"
                        "    \"param-disableslorightcolor\": \"1\",\n"
                        "    \"param-disparitymode\": \"0\",\n"
                        "    \"param-disparityshift\": \"0\",\n"
                        "    \"param-lambdaad\": \"751\",\n"
                        "    \"param-lambdacensus\": \"6\",\n"
                        "    \"param-leftrightthreshold\": \"10\",\n"
                        "    \"param-maxscorethreshb\": \"2893\",\n"
                        "    \"param-medianthreshold\": \"796\",\n"
                        "    \"param-minscorethresha\": \"4\",\n"
                        "    \"param-neighborthresh\": \"108\",\n"
                        "    \"param-raumine\": \"6\",\n"
                        "    \"param-rauminn\": \"3\",\n"
                        "    \"param-rauminnssum\": \"7\",\n"
                        "    \"param-raumins\": \"2\",\n"
                        "    \"param-rauminw\": \"2\",\n"
                        "    \"param-rauminwesum\": \"12\",\n"
                        "    \"param-regioncolorthresholdb\": \"0.785714\",\n"
                        "    \"param-regioncolorthresholdg\": \"0.565558\",\n"
                        "    \"param-regioncolorthresholdr\": \"0.985323\",\n"
                        "    \"param-regionshrinku\": \"3\",\n"
                        "    \"param-regionshrinkv\": \"0\",\n"
                        "    \"param-robbinsmonrodecrement\": \"25\",\n"
                        "    \"param-robbinsmonroincrement\": \"2\",\n"
                        "    \"param-rsmdiffthreshold\": \"1.65625\",\n"
                        "    \"param-rsmrauslodiffthreshold\": \"0.71875\",\n"
                        "    \"param-rsmremovethreshold\": \"0.809524\",\n"
                        "    \"param-scanlineedgetaub\": \"13\",\n"
                        "    \"param-scanlineedgetaug\": \"15\",\n"
                        "    \"param-scanlineedgetaur\": \"30\",\n"
                        "    \"param-scanlinep1\": \"155\",\n"
                        "    \"param-scanlinep1onediscon\": \"160\",\n"
                        "    \"param-scanlinep1twodiscon\": \"59\",\n"
                        "    \"param-scanlinep2\": \"190\",\n"
                        "    \"param-scanlinep2onediscon\": \"507\",\n"
                        "    \"param-scanlinep2twodiscon\": \"493\",\n"
                        "    \"param-secondpeakdelta\": \"647\",\n"
                        "    \"param-texturecountthresh\": \"0\",\n"
                        "    \"param-texturedifferencethresh\": \"1722\",\n"
                        "    \"param-usersm\": \"1\",\n"
                        "    \"param-zunits\": \"1000\",\n"
                        "    \"stream-depth-format\": \"Z16\",\n"
                        "    \"stream-fps\": \"30\",\n"
                        "    \"stream-height\": \"720\",\n"
                        "    \"stream-width\": \"1280\"\n"
                        "}");
    return preset_json;
}
