#!/bin/bash

cd /home/fulfil/code
if [[ "$USER" == "root" ]] ; then
    docker compose stop depthcam && docker compose stop bgredisworker && docker compose stop traycount
    runuser -l fulfil -c 'dc-startup kill'
    runuser -l fulfil -c 'dc-startup'
    exit $?
fi


docker compose stop depthcam && docker compose stop bgredisworker && docker compose stop traycount
dc-startup kill
dc-startup
