#!/bin/bash

echo "Running as $USER!"

cd /home/fulfil/code
# Kill any existing sessions to prevent resource competition and crashing the computer

docker compose stop depthcam && docker compose stop bgredisworker && docker compose stop traycount
echo "Live sessions:"
docker ps

if [[ "${1}" == "kill" ]] ; then 
	exit 0
fi

# TODO: do we need this on the host OS?
#rs-fw-update -l

docker compose start depthcam && docker compose start bgredisworker && docker compose start traycount
docker ps
DELAY=5
echo "Live-tailing depthcam sessions in $DELAY second(s)! API may require restart in session."
docker compose logs depthcam -f
